### ISSUE TITLE
Help Message with Nested Commands

### ISSUE THREAD

**Issue by sschepens** [alecthomas/kingpin#10]
When there are many nested subcommands the Usage information is huge and impossible to understand.
I was thinking of a different approach to Usage information and I would like to propose it.
I think it Application Usage could be greatly simplified by making Usage print only the first set of available commands.
Then, It would be great too if when specifying a correct first command but no subsequent subcommands we could show the Usage for that specific command instead of the whole app.
And so on, instead of having the Application print every possible combination of commands, we could just show the next step in the tree of combinations.

Instead of:
`app` would print:

```
app
Flags:
Commands:
delete user [<flags>]
delete post [<flags>]
```

For example:
`app` would print:

```
app
Flags:
Commands:
delete <command>
```

`app delete` would print:

```
app delete
Flags:

Commands:
user [<flags>]
post [<flags>]
```

I dont know if i make myself clear.
Hope you like my proposal
Cheers!

**Comment by alecthomas** [comment]
I'm actually thinking of having two separate flags for help. The default would be compact, perhaps just listing all commands recursively like so:

```
app --help
Flags:
  ...
Commands:
    delete [<flags>] ...
        user [<flags>] <user>
        post [<flags>] <post>
    create post <text>
```

Then `--help-full` would list fully expanded help, with all available flags and commands.

**Comment by alecthomas** [comment]
I'm still not sure what the right approach is, so I'll defer this for a bit.

**Comment by wwalker** [comment]
Just my input.  I like the help information now.  I'd prefer to get long help by default.
Maybe, if the total lines of help exceeds some number (24?) of lines, make the last line of --help output:
  --help-short for more compact help

**Comment by alecthomas** [comment]
I'm halfway through the template based approach and the following is the current default output. I'm fairly happy with it. I will probably not provide other help formats, as it makes maintenance more difficult, but I will document the help template context.

```
$ go run ./examples/curl/curl.go --help
usage: curl [<flags>] <command> [<args> ...]

An example implementation of curl.

Flags:
  --help            Show help.
  -t, --timeout=5s  Set connection timeout.
  -H, --headers=HEADER=VALUE
                    Add HTTP headers to the request.

Commands:
  get url <url>
    Retrieve a URL.

  get file <file>
    Retrieve a file.

  post [<flags>] <url>
    POST a resource.


$ go run ./examples/curl/curl.go --help get
usage: curl get [<flags>] <command> [<args> ...]

GET a resource.

Flags:
  --help            Show help.
  -t, --timeout=5s  Set connection timeout.
  -H, --headers=HEADER=VALUE
                    Add HTTP headers to the request.
  --test            Test flag

Commands:
  get url <url>
    Retrieve a URL.

  get file <file>
    Retrieve a file.


$ go run ./examples/curl/curl.go --help get url
usage: curl get url [<flags>] <url>

Retrieve a URL.

Flags:
  --help            Show help.
  -t, --timeout=5s  Set connection timeout.
  -H, --headers=HEADER=VALUE
                    Add HTTP headers to the request.
  --test            Test flag

Args:
  <url>  URL to GET.

$ go run ./examples/curl/curl.go --help post
usage: curl post [<flags>] <url>

POST a resource.

Flags:
  --help            Show help.
  -t, --timeout=5s  Set connection timeout.
  -H, --headers=HEADER=VALUE
                    Add HTTP headers to the request.
  -d, --data=KEY:VALUE
                    Key-value data to POST
  --data-binary=DATA-BINARY
                    File with binary data to POST.

Args:
  <url>  URL to POST to.
```

**Comment by sschepens** [comment]
I think this looks good and will definitely be good to add templating

**Comment by alecthomas** [comment]
Okay. If you check out the [v2-model](https://github.com/alecthomas/kingpin/compare/v2-unstable...v2-model) branch I'd be interested in seeing if this is sufficient for your help requirements. You can find the template context [here](https://github.com/alecthomas/kingpin/compare/v2-unstable...v2-model#diff-3472cb4e0a973362a7dbc843481a069eR141).

**Comment by alecthomas** [comment]
The v2-unstable branch is currently pretty much feature complete, except for the merging of the model stuff, which I'm still not 100% sure about. It complicates the code for what is (potentially) a relatively minor improvement.

**Comment by alecthomas** [comment]
I ended up compromising and adding an `Application.Model()` function that builds a public model from the internal representation. I've also provided two usage templates: the default and a compact command representation that outputs something like this:

```
usage: curl [<flags>] <command> [<args> ...]

An example implementation of curl.

Flags:
  --help            Show help.
  -t, --timeout=5s  Set connection timeout.
  -H, --headers=HEADER=VALUE
                    Add HTTP headers to the request.

Commands:
  help [<command>...]
  get [<flags>]
    url <url>
    file <file>
  post [<flags>] <url>
```

**Comment by sschepens** [comment]
You're awesome!

**Comment by alecthomas** [comment]
Thanks! I also just added a hidden `--man-page` flag that generates man pages using the templating system.
