### ISSUE TITLE
Ability to turn off placeholders

### ISSUE THREAD

**Issue by kontsevoy** [alecthomas/kingpin#100]
Hey there. Love your library!
There is one thing though which causes lots of unnecessary work:

I want a _clean_ output for my flags, like this:

```
  --username      username flag help 
```

Right now I get this:
```
  --username=USERNAME   username flag help
```

So I had to clone kingpin repo and manually remove the addition of a non-existing placeholder (inside of `formatFlag()`). It would be nice to have a way to turn it off completely.

Thanks!

P.S. I kind of get the intended purpose of placeholders, but (at least for my purpose) seeing a bunch of uppercased flag names confuses people and I cannot come up with a usable explicit placeholders (besides, they cause newlines for each flag line in `help` output - another problem I've been trying to fight with custom templates, but unsuccessfully)

**Comment by kontsevoy** [comment]
Created a pull request:
https://github.com/alecthomas/kingpin/pull/101

I hope it's idiomatic enough to be accepted.
Thanks!

**Comment by alecthomas** [comment]
> I want a clean output for my flags, like this:
>  --username      username flag help 

The problem with this is that there's no way for a user to differentiate between a boolean flag and a flag that takes an argument.

If your main concern is the length, why not just do `.Placeholder('?')`, which would result in:

    --username=?  username flag help

This is only two more characters than removing the placeholder entirely. It is a bit tedious having to specify a placeholder for every flag though.

> P.S. I kind of get the intended purpose of placeholders, but (at least for my purpose) seeing a bunch of uppercased flag names confuses people and I cannot come up with a usable explicit placeholders (besides, they cause newlines for each flag line in help output - another problem I've been trying to fight with custom templates, but unsuccessfully)

They only cause newlines if the length of the flag part is > 30 characters. Unfortunately this is hardcoded in `formatTwoColumns()`, but 30 characters is almost half an 80 column terminal, so it seems fairly reasonable.

**Comment by kontsevoy** [comment]
Alec,

Thanks for the prompt response.

> They only cause newlines if the length of the flag part is > 30 characters. 

True, and we consistently blow past that limit because:
- Identation is a part of 30 char limit
- Short flags (we love have those) further add to it
- We want to have some space between the _longest_ flag and the description, at lest 2-3 spaces

To better illustrate what I'm dealing with, here's the format we're going after (real world usage):
```
Flags:
  -p, --profile         Name of profile from ~/.tshconfig
  -h, --proxy-host      SSH proxy (bastion) hostname/IP 
      --proxy-port      SSH proxy (bastion) port [3023]
      --proxy-user      Bastion username [same as your local username]
      --login-ttl       Time to live for a temporary SSH certificate. Defaults to a server setting.
```
As you can see:
1. We prefer to show placeholders `[in brackets]` at the end of the description, especially because/when they're not trivial - see example below. not to argue about personal preferences, but we just like this better. ;-)
2. we do not use boolean flags much, and even if we had them, they're usually the easiest to understand (we'd have `[yes]` or `[no]` as their default value in the description).

Anyway, the proposed change does not add much complexity in terms of code, but significantly enhances flexibility of the library in a way that's consistent (I hope) with its design.

**Comment by kontsevoy** [comment]
[edited my comment above to add more relevant flags from our real world use case]

**Comment by alecthomas** [comment]
As the change discussed in #101 would be a breaking one, I've moved this to the v3 feature list.
