### ISSUE TITLE
(*FlagClause).Strings cannot have multiple values in an Envar

### ISSUE THREAD

**Issue by belak** [alecthomas/kingpin#102]
There is currently no way to specify `.Strings` in an environment variable in such a way that multiple values will be returned.

**Comment by alecthomas** [comment]
I believe each new line in the envar will be a separate value, though perhaps this is not documented.

**Comment by belak** [comment]
Ah, I assumed commas would work, but they're just returned as a single string. I didn't try newlines.

**Comment by duggan** [comment]
I find newlines are a bit of an awkward character for environment variables (they rarely pass unmolested through configuration, and are tricky to get in even by hand). Is that just me?

Might be ideal if this were configurable, though I think comma separation would be a sensible addition one way or another.

**Comment by alecthomas** [comment]
I agree, and it would be great to be able to change the default, but that would also mean that every flag would need to hold a reference to either this setting or a generic settings struct.

Another option might be to just pick something like comma or semi-colon, but allow it to be escaped.

**Comment by rahulpowar** [comment]
Is the newline behaviour with Envar() and Strings() working? I seem to be getting an array of length 1 with the newline chars in that string entry.
