### ISSUE TITLE
Feature Request Exclusive groups support

### ISSUE THREAD

**Issue by aacebedo** [alecthomas/kingpin#103]
Hi
First of all your library is great! In python I'm using Argparse and kingpin when working with golang.  
However I am missing a neat feature of Argparse: exclusive args groups. Do you consider adding it in v3? 

Regards.

**Comment by alecthomas** [comment]
Thanks! What is an exclusive group?

**Comment by aacebedo** [comment]
You can check argparse documentation for more detail:
https://docs.python.org/3/library/argparse.html section "16.4.5.4. Mutual exclusion"

**Comment by alecthomas** [comment]
I've added this to the v3 feature list. Good idea.

**Comment by aacebedo** [comment]
Great ! thank you.

Le mer. 17 févr. 2016 à 11:27, Alec Thomas <notifications@github.com> a
écrit :

**Comment by tiedotguy** [comment]
You can sort of do this with a wrapper:
```
// mutuallyExclusive will wrap a kingpin.Value, and use the provided *bool to track if a mutually exclusive flag
// has already been invoked.  If it has, the error will be returned.
type mutuallyExclusive struct {
	b     *bool
	error string
	value kingpin.Value
}

func (m *mutuallyExclusive) String() string {
	return m.value.String()
}

func (m *mutuallyExclusive) Set(s string) error {
	if *m.b {
		return errors.New(m.error)
	}
	*m.b = true
	return m.value.Set(s)
}

func newMutuallyExclusive(value kingpin.Value, b *bool, error string) kingpin.Value {
	return &mutuallyExclusive{
		b:     b,
		error: error,
		value: value,
	}
}
```

Then consume with:
```
var mutexAbcDef bool
c.Flag("abc", "thing with abc").SetValue(newMutuallyExclusive(newAbcValue(&abc), &mutexAbcDef, "--abc and --def can't both be provided"))
c.Flag("def", "thing with def").SetValue(newMutuallyExclusive(newDefValue(&def), &mutexAbcDef, "--abc and --def can't both be provided"))
```

Unfortunately the built-in parsers aren't exported, so you'll need to copy them out so you can wrap them (unless there's some other way to wrap them, I'm not super familiar)
