### ISSUE TITLE
ability to support X Java style long args (-example)

### ISSUE THREAD

**Issue by wwalker** [alecthomas/kingpin#109]
I would not want single dash long flags (e.g. -props rather than --props) to be default supported, because it precludes clean POSIX-style short flag combining.

However, I would love to be able to turn on support for single dash long arguments.

**Comment by alecthomas** [comment]
I don't think I'd like Kingpin to support this as a) it would make the code much more complex and b) Kingpin tries to adhere closely to POSIX/GNU-style flags as closely as possible.
