### ISSUE TITLE
Please drop dependency on "github.com/alecthomas/template"

### ISSUE THREAD

**Issue by onlyjob** [alecthomas/kingpin#117]
If `github.com/alecthomas/template` is [going to disappear](https://github.com/alecthomas/template/issues/3#issuecomment-188537775) it would be great to stop depending on it. Thanks.

FYI @petercolberg.

**Comment by alecthomas** [comment]
It is not disappearing it's just in maintenance mode. Text/template can replace it under Go 1.6 but it will remain for <1.6 support.

Also, it has already been removed in the v3 branch.

**Comment by petercolberg** [comment]
For reference, this issue has already been resolved in #114.

**Comment by onlyjob** [comment]
Fantastic, thanks. Can we please also have a release version bump?

**Comment by alecthomas** [comment]
V3 is under development. You can get it via gopkg but while under development it will break regularly.

**Comment by alecthomas** [comment]
The [v3 development branch](https://github.com/alecthomas/kingpin/tree/v3-unstable) is available under `gopkg.in/alecthomas/kingpin.v3-unstable`.
