### ISSUE TITLE
feature request: min length, max length, and whitespace trimming

### ISSUE THREAD

**Issue by insasho** [alecthomas/kingpin#125]
The `.String()` type is versatile, but often it is more permissive than we want. For example, some flags might have a maximum or minimum length. Minimum length is not naturally expressed with `.Required()` as that implies a minimum length of 1 and does not trim whitespace.

Suggestion: Add some modifiers to FlagClause such as:
   a. `MinLength` to enforce a min length
   b. `MaxLength` to enforce a max length
   c. `Trimmed` to always whitespace-trim the flag before processing

Using custom `flag.Value` types doesn't appear to be an elegant solution to this problem because:
1. they are awkward to chain, leading to a proliferation of flag-specific `flag.Value` implementations
2. errors returned by `.Set` are not displayed by kingpin with the flag name prefixed, which makes implementation of useful error messages awkward. For example, a `return fmt.Errorf("max length of %d exceeded", m.maxLength)` from a `flag.Value` `.Set()` prints
```
progname: error: max length of 24 exceeded, try --help
```
It would be nice if this also contained the name of the flag that was being validated.

If I misunderstood how Kingpin is to be used, please send me in the right direction. I see v1.3.4 added "Add post-app and post-cmd validation hooks. This allows arbitrary validation to be added." but I couldn't find any examples or additional docs on this.

Thanks!

**Comment by insasho** [comment]
After additional investigation, it looks like `.Action()`, `.PreAction()`, and `.Validate()` methods are also inappropriate for applying custom validation to user-provided strings because the actual string value is awkward to extract from the data structures made available to those methods. The `Validate` API allows identifying a FlagClause by name, though the `Action` API requires searching over `c.Elements` manually. In both cases, retrieving the actual value is impossible because `.value` is not exported and there is no getter. Am I missing something?

Thanks!

**Comment by alecthomas** [comment]
Hi there. Yes, the actions and Validate methods were poorly thought out. Fixing that is the first item in the v3 wish list (#90).

I don't think adding functions for specific types of validation is the right approach though, but fixing the Validate functions is.

I've added a link to this issue for details.

Thanks for the report.

**Comment by ches** [comment]
> the actual string value is awkward to extract from the data structures made available to those methods. The `Validate` API allows identifying a FlagClause by name, though the `Action` API requires searching over `c.Elements` manually. In both cases, retrieving the actual value is impossible because .value is not exported and there is no getter.

I've had the same thoughts when trying to figure out how to use these, I'm glad it's not just me 😄  For instance, where does the `error` that my `Action` returns go/how is it handled, and how can I actually get at values with `Validate`? There were no unit tests or examples added for `Validate` to shed light.

I'll look forward to v3 for these 😄
