### ISSUE TITLE
Only the default command is visible in the `--help` result

### ISSUE THREAD

**Issue by szank** [alecthomas/kingpin#126]
Hi, I have an app with two commands: 
```
var app = kingpin.New("app", "")
	var generateCommand = app.Command("generate", "something").Default()
	var buildCommand = app.Command("build", "something else")
[...]
```

What I can see after i call `./app --help` is : 
```
usage: app generate [...]

something else

Flags:
[...]
```

There is no information about the second `build` command there. Am I missing something, last time I checked there were no flags that would hide the non default commands?

**Comment by alecthomas** [comment]
Thanks, good find.
