### ISSUE TITLE
Allow enforcing unique values for repeated flags 

### ISSUE THREAD

**Issue by szank** [alecthomas/kingpin#127]
Hi, 
Currently when using flag types like EnumVars(...) , Ints(...), Strings(...) there is no way to tell kingpin to return an error if identical value is passes more than once. 

This check could be disabled by default, it it would be nice if I didn't have to do it manually every time I need it.

**Comment by alecthomas** [comment]
There is no means of configuring values beyond the function name (Ints, Strings, etc.) so supporting this would require StringSet, IntSet, and so on. This is not really feasible.

However, for v3 I am planning on supporting the passing of options to these functions. Example in #90 .
