### ISSUE TITLE
HintOptions for Args

### ISSUE THREAD

**Issue by Mange** [alecthomas/kingpin#131]
I'd like to have `HintOptions` for an `Arg`.

Example usage:

```
./move <DIRECTION>
```

where `DIRECTION` could give hints on `up`, `north`, and so on.

It's currently only possible to add `HintOptions` on `Flag`s AFAIK.

**Comment by Mange** [comment]
I see now that it's present in `master`. 😄 

I guess we can keep this open until that version has been released..?

**Comment by alecthomas** [comment]
Pushed 2.2.0!

**Comment by Mange** [comment]
👏👍

Den tis 12 juli 2016 06:18Alec Thomas <notifications@github.com> skrev:
