### ISSUE TITLE
Allow extending of funcmap for templates

### ISSUE THREAD

**Issue by josephspurrier** [alecthomas/kingpin#132]
Brilliant package! You just saved me boatloads of time because my command-line app needed to be really flexible and your package does the majority of the work so I can focus on functionality.

I'd like to modify the way .Context.Args displays in the UsageTemplate. I would like the variable type (string/bool) and the default to display next to the help string.

Is this functionality built in somewhere or would it make sense to add the ability to extend the funcmap in UsageForContextWithTemplate?

**Comment by alecthomas** [comment]
Absolutely agreed, this is slated for v3 and tracked in #90.

**Comment by josephspurrier** [comment]
Cool, thanks!
