### ISSUE TITLE
Feature request: Accept multiple values for flag like the result of a glob

### ISSUE THREAD

**Issue by nickcarenza** [alecthomas/kingpin#135]
Since go doesn't support ** globs, i want to leverage shell glob like this:

`cmd --paths ./**/*.json` -> `cmd --paths ./a/1.json ./a/2.json`

I'd like not to have to specify `--paths` before each expansion.

Possible methods:

```
kingpin.Flag("paths", "list of paths").List().ExistingFiles()
kingpin.Flag("paths", "list of paths").Multiple().ExistingFiles()
kingpin.Flag("paths", "list of paths").Long().ExistingFiles()
```

**Comment by nickcarenza** [comment]
Alternatively `Glob()` could be a new method like `ExistingFiles()` that supported `**` but I originally thought that the difference wouldn't be clear for people.

**Comment by alecthomas** [comment]
The problem with this approach is that differentiating between these types of flags and positional arguments becomes ambiguous. eg.

```
pathsFlag = kingpin.Flag("paths", "List of paths.").ExistingFiles()
args = kingpin.Arg("name", "Username").String()
```

```
cmd --paths a b c username
```

The user could use `--`, but that is not obvious.

The typical/recommended way to achieve what you want (and AFAICT this is also true with most other arg parsing libraries) is with something like the following:

```
deleteFlag = kingpin.Flag("delete", "Delete files.").Bool()
moveFlag = kingpin.Flag("move", "Move files.").Bool()
usernameArg = kingpin.Arg("username", "User name.").Required().String()
filesArg = kingpin.Arg("files", "Files to operate on.").Required().ExistingFiles()
```

```
cmd --delete alec ./**/*.json
```

**Comment by nickcarenza** [comment]
I see. You are correct. I think I am going to have to implement a special **-glob-parsing function myself. Would you be interested in the alternative method I suggested with that implementation `FlagClause.Glob()`?
