### ISSUE TITLE
`--help` incorrectly exits with exit code 1

### ISSUE THREAD

**Issue by lox** [alecthomas/kingpin#136]
Correctly calling `--help` shouldn't fail with exit code 1, it should be exit code 0. With the test program:

```golang
var (
  verbose = kingpin.Flag("verbose", "Verbose mode.").Short('v').Bool()
  name    = kingpin.Arg("name", "Name of user.").Required().String()
)

func main() {
  kingpin.Parse()
  fmt.Printf("%v, %s\n", *verbose, *name)
}
```

```bash
 ~  › go run test.go --help
usage: test [<flags>] <name>

Flags:
      --help     Show context-sensitive help (also try --help-long and --help-man).
  -v, --verbose  Verbose mode.

Args:
  <name>  Name of user.

exit status 1
✗ exit 1
```

**Comment by alecthomas** [comment]
Why?

**Comment by lox** [comment]
Yeah, I asked myself that same question and hunted through various POSIX things to see if there was a definitive answer. In the end I just checked the behaviour of lots of linux utils and they all behave this way. If you've asked for help, it makes sense to me that you get an non-error exit code. If you have incorrect usage and are shown help, then you'd expect an error exit code.

**Comment by alecthomas** [comment]
Yeah that's the behaviour I've gone with: --help exits with 0 while an error that results in usage exits with 1.

**Comment by lox** [comment]
Thanks for the quick turnaround and the great library :)
