### ISSUE TITLE
`--version` should always use stdout

### ISSUE THREAD

**Issue by lox** [alecthomas/kingpin#137]
It seems to me like `--version` should always use stdout, rather than rely on `a.writer`, like the bash completion built-in flags. 

Code here: https://github.com/alecthomas/kingpin/blob/master/app.go#L238

My thinking is it should be more like: https://github.com/alecthomas/kingpin/blob/master/app.go#L99

Thoughts?

**Comment by lox** [comment]
Incidently, should the following work to output `--version` to stdout?

```
package main

import (
        "fmt"

        "github.com/alecthomas/kingpin"
)

var (
        verbose = kingpin.Flag("verbose", "Verbose mode.").Short('v').Bool()
        name    = kingpin.Arg("name", "Name of user.").Required().String()

        Version = "1.0.0"
)

func main() {
        kingpin.CommandLine.Writer(os.Stdout)
        kingpin.Parse()
        fmt.Printf("%v, %s\n", *verbose, *name)
}
```

It doesn't appear to on v2.2.0.

**Comment by alecthomas** [comment]
Yep, agreed, this is tracked in #90. Though, actually I think I'll just do it now. It's not breaking enough to wait for v3.
