### ISSUE TITLE
How to check if an Arg has been setted

### ISSUE THREAD

**Issue by k0pernicus** [alecthomas/kingpin#140]
Hi there!

I'm trying to implement a CLI that responds to `mypgm add --path="../HelloWorld.md"`.  
This command can also take as parameter `--group` like `mypgm add --group="../mygroup/"`.

I don't understand how works args, and I'm continuing to check how to launch my program using args in command :-/

Currently, I check if `path` has been setted using `if path != nil {...` but it seems it does not work

**Comment by k0pernicus** [comment]
Ok so it seems that, if I want to check if an Arg has been setted, I have to check `if *pointerToArg != "" {...` (which is ugly :-().

**Comment by k0pernicus** [comment]
Also, is it possible to explicity set the argument?

For example: `mypgm add --groupe="HelloWorldUsers"` and `mypgm add --path="./"` ?

Thanks!

**Comment by k0pernicus** [comment]
Ok, finally I updated my code to use flags instead of args and it works well! \o/

**Comment by lespea** [comment]
It would be cooler if the value was nil if it wasn't set instead of a pointer to the default value imo.
