### ISSUE TITLE
Example for v2 refers to v1

### ISSUE THREAD

**Issue by JensRantil** [alecthomas/kingpin#142]
The example on https://godoc.org/gopkg.in/alecthomas/kingpin.v2 contains

    "gopkg.in/alecthomas/kingpin.v1"

. Should probably be

    "gopkg.in/alecthomas/kingpin.v2"

**Comment by alecthomas** [comment]
FYI you can edit files in GitHub to create a PR. With this method you could create a PR as quickly as writing an issue.
