### ISSUE TITLE
Change FlagClause.Default arg to ...interface{}

### ISSUE THREAD

**Issue by willfaught** [alecthomas/kingpin#150]
This would allow, for example, Default(os.Stdin).File().

**Comment by alecthomas** [comment]
The default value is always parsed by [Value.Set()](https://godoc.org/gopkg.in/alecthomas/kingpin.v2#Value), so it *must* be a string.

On unix-like systems you should be able to use "/dev/stdin" for this particular case.

**Comment by willfaught** [comment]
No Windows support though, as you mentioned.

**Comment by alecthomas** [comment]
Have you tried `os.Stdin.Name()`? This works on *nix.

**Comment by willfaught** [comment]
Yes, I think it would work in that case. It's OK, it just requires a little extra logic after the parsing to handle.
