### ISSUE TITLE
Dynamic flags?

### ISSUE THREAD

**Issue by willfaught** [alecthomas/kingpin#151]
Is there a way to enable dynamic string flags such that you don't know beforehand what the flag names and variables will be, or how many of them there will be? For example, --foo bar --country iceland --a b. In my particular case, this would be for defining the fields of a JSON object that has no expected schema.

Sorry if I missed this in the README and doc.

**Comment by alecthomas** [comment]
I don't quite understand your example, but once you call `Parse()` there's no real way to add new flags, if that's what you're asking for.

**Comment by willfaught** [comment]
var f = ...Flag("foo"...)...Bool()
var g = ...Flag("bar"...)...Int()
var rest = ...Rest()
...Parse()...
./app --foo --bar 23 --apple yum --banana gross
fmt.Println(\*f) // true
fmt.Println(\*g) // 23
for k, v := range \*rest { fmt.Println(k, v) } // apple yum // banana gross

**Comment by alecthomas** [comment]
No, that is not supported. The closest you can achieve is by using [StringMap()](https://godoc.org/gopkg.in/alecthomas/kingpin.v2#FlagClause.StringMap) which would allow:

`--fruit apple=yum --fruit banana=gross`
