### ISSUE TITLE
Arg/flag dependencies

### ISSUE THREAD

**Issue by willfaught** [alecthomas/kingpin#154]
It'd be useful to be able to express that certain not-required args or flags are required only if other args or flags are given. For example, given the flags "name" and "type", type can be given by itself or not at all, but if name is given, then type must be given too. Something like:

    Flag("type"...)...
    Flag("name"...).RequireFlag("type")...

I imagine you could do the same for not-required-by-default arguments:

    Arg("foo"...)...
    Flag("bar"...).RequireArg("foo")

**Comment by alecthomas** [comment]
Similar requirements have been brought up in the past and I think the best general-purpose solution is to put this kind of logic in [Application.Validate](https://godoc.org/gopkg.in/alecthomas/kingpin.v2#Application.Validate).

**Comment by willfaught** [comment]
Thanks.
