### ISSUE TITLE
Support flag aliasing

### ISSUE THREAD

**Issue by hlandau** [alecthomas/kingpin#157]
Short aliases are supported, but general-purpose flag aliases would be desirable. In particular, aliases should be hideable. The use case here is that flag `--foo` is currently supported, and you want to rename it to `--bar` and stop advertising `--foo`, but need to continue accepting `--foo` for backwards compatibility.

**Comment by alecthomas** [comment]
While not as convenient as first class flag aliases, you can achieve what you want with the following:

```go
var (
  bar = kingpin.Flag("bar").Bool()
)

func init() {
  kingpin.Flag("foo").Hidden().BoolVar(bar)
}
```

**Comment by alecthomas** [comment]
Closing, but reopen if you have a good argument for first-class support.
