### ISSUE TITLE
Negative arguments get mistaken for short flags

### ISSUE THREAD

**Issue by pritambaral** [alecthomas/kingpin#166]
For an invocation matching:

```
app cmd <arg>
```

where `arg` happens to be a negative number:

```
app cmd -1
```

The `-1` is mistaken for a short flag, and the following error appears:

```
app: error: unknown short flag '-1', try --help
```
The error appears even when `app.Interspersed(false)` has been used.

While it is possible to use a ` -- ` separator to explicitly end all flag parsing, it is not obvious from help.

Wouldn't it be better to see if the token matches an arg, and if yes, then suppress it?

**Comment by alecthomas** [comment]
So what happens if "-1" is actually a flag? How would you pass that as an argument?

**Comment by alecthomas** [comment]
I mean, this is traditionally what `--` is designed for.

**Comment by pritambaral** [comment]
> So what happens if "-1" is actually a flag? How would you pass that as an argument?

It makes sense when "-1" can match a flag.

It is an issue only when "-1" can not match a flag, which is how I came across this.

**Comment by alecthomas** [comment]
Right, but I'm asking if -1 is a flag, but you also want to pass it as an argument? I don't think there's a "right" answer here beyond "use --".

**Comment by pritambaral** [comment]
> but I'm asking if -1 is a flag, but you also want to pass it as an argument?

No.
I want to pass it as an argument when it couldn't possibly match a flag. As I said in the very first line of my description of the issue:

> For an invocation matching:
> ```
> app cmd <arg>
> ```

Not, `app [flags] cmd [flags] <arg>`.

**Comment by alecthomas** [comment]
Yes, I understand what you're saying. But I'm asking you a broader question in return. Anyway, no, I don't think this is a good idea, as it isn't a general solution to this problem.
