### ISSUE TITLE
go test fails when Parse inside init()

### ISSUE THREAD

**Issue by chambo-e** [alecthomas/kingpin#167]
Hello, 

I'm facing a strange behaviour when trying to test my programs.

main.go
```
package main

import kingpin "gopkg.in/alecthomas/kingpin.v2"

func init() {
	kingpin.Parse()
}

var (
	toto = kingpin.Flag("test", "Test").String()
)
```

main_test.go
```
package main

import "testing"

func TestTest(t *testing.T) {}
```

When I try to execute my test with 
```shell
$ go test
```
it works.
But with flags it fails
```
$ go test -v --sort
test.test: error: unknown short flag '-t', try --help
exit status 1
FAIL	github.com/chambo-e/test	0.009s
```

I assume this is because of the flags the `go test` command pass to the programs:
```shell
test.test -test.short=true -test.v=true
```

And I was wondering if there was a way to make this works ?
Thanks :)

**Comment by alecthomas** [comment]
Go's test functionality parses the command line with the built-in flag package, you will have to add flags with that.
