### ISSUE TITLE
Strange results with repeated parsing of help commands

### ISSUE THREAD

**Issue by mkarlesky** [alecthomas/kingpin#169]
Thanks so much for Kingpin. It's a great package. I'm using it in two different ways in the same project. Except for this present issue, it's meeting the needs of my project handily.

I'm using Kingpin both as a traditional command line processor for individual command line applications and again separately as a command string processor in a networked application. Unlike the former use case, in the latter use case, Kingpin's command line parsing is called repeatedly; command parsing errors do not cause the networked application to exit.

Instantiating Kingpin and making multiple parse calls against it is working just fine in the networked application with one specific exception. Repeated calls to help commands seem to somehow corrupt tokenization and lead to incorrect help messages and the unexpected reporting of parsing errors.

Consider the following call progression:

1. `foo help bar`
2. `foo help bar`
3. `foo help baz`
4. `foo help bar`
5. `foo help baz`

The help returned for (1) and (2) will be spot-on correct and identical. Call (3) _might_ work as expected. Calls to (4) and (5) will certainly exhibit the reported behavior. (5) will show the help message for the `bar` command instead of the `baz` command. In addition, (4) and (5) will both report error conditions concerning an unexpected token after the EOL token (“unexpected baz”) [emitted from lines 368–370 in the latest version of parser.go].

I've gone spelunking through the code and tried to trace out the processing of tokenization with `println()` calls to figure out what's going on. It's all a bit too nuanced for me to readily grasp the finer details. From what I can tell it appears that parsing context is persisting and the handling of help commands (using repeated parsing?) is not fully cleaning up that parsing context.

Unlike help handling, the repeated parsing of command strings that trigger actions seems to work without any issue.

Am I missing a necessary reset / cleanup step? Was Kingpin not meant to be called repeatedly in an interactive application such as I am trying to do?

**Comment by alecthomas** [comment]
Interesting. That is not a use-case that Kingpin typically supports, but I wouldn't want it to be corrupting and it should work. It does not 100% surprise me that help does this, as it's quite a complex. Can you come up with a test case?

**Comment by mkarlesky** [comment]
Attached is a small example that exercises Kingpin “interactively” using stripped down code from my project. The test app first prints top-level usage. Then the app makes multiple calls to `help` for two commands. Finally, for good measure, the app executes the two actions attached to the commands. The output I see when running this little app is at bottom.

[kingpin-test.zip](https://github.com/alecthomas/kingpin/files/640824/kingpin-test.zip)

The meat of the test case is found in calling `help` 3 times for 2 commands ‘foo’ and ‘bar’:

1. `help foo`
2. `help foo`
3. `help bar`

The result of the first call is as expected. The result of the second call produces the correct help message but reports an unexpected token beyond the end of the command. The result of the third call produces a help message for foo instead of bar and reports a token beyond the end of the command string as well.

Thanks so much for any help in figuring this out.

```=== Usage() ===

usage: kingpin-test [<flags>] <command> [<args> ...]

Testing a help parsing bug

Flags:

Commands:
  help [<command>...]
    Show help.

  foo
    Foo does some serious fu

  bar
    Bar does it up



-----------

=== "help foo" ===

usage: kingpin-test foo

Foo does some serious fu

Flags:


-----------

=== "help foo" ===

kingpin-test: error: unexpected foo
usage: kingpin-test foo

Foo does some serious fu

Flags:


-----------

=== "help bar" ===

kingpin-test: error: unexpected foo
usage: kingpin-test foo

Foo does some serious fu

Flags:


-----------

=== fooDoer() ===

=== barDoer() ===
```

**Comment by alecthomas** [comment]
Okay, I finally got a chance to look into this and... I'm still not sure why it happens, but it is fixed in kingpin.v3-unstable. If you can, I would suggest using that, as it will be the next major release of kingpin anyway. You can see the changes to your test case that I had to make, in [this gist](https://gist.github.com/alecthomas/f5e2c88dde5dc20b1d3cead94d246189/revisions).

**Comment by mkarlesky** [comment]
I have been able to try v3-unstable. The updated version of my test example works as advertised, and updating my project to use v3-unstable was quite straightforward. No big issues.

While the example I provided is now running properly I've found that the bug has just been moved around a bit. It seems a token is still getting leftover in the help command processing. `help` followed by `help foo` will work correctly. `help foo` followed by `help` will produce the help for foo in both instances. It seems as though the longest executed help command hangs around in memory.

I've attached an updated version of the example we've been working with that demonstrates the behavior.

Thanks again for a great library and for taking the time to investigate this little issue.

[kingpin-test.zip](https://github.com/alecthomas/kingpin/files/705069/kingpin-test.zip)

**Comment by alecthomas** [comment]
Here is a minimal failing test case:

```go
func TestIssue169MultipleUsageCorruption(t *testing.T) {
	buf := &bytes.Buffer{}
	app := newTestApp()
	cmd := app.Command("cmd", "")
	cmd.Flag("flag", "").Default("false").Bool()
	app.Writer(buf)
	_, err := app.Parse([]string{"help", "cmd"})
	assert.NoError(t, err)
	expected := buf.String()

	buf.Reset()
	_, err = app.Parse([]string{"help"})
	assert.NoError(t, err)
	actual := buf.String()

	assert.NotEqual(t, expected, actual)
}
```

**Comment by alecthomas** [comment]
As an aside, you may also be interested in 801d8e545ccdde3fcaaec3ddafc4827969635aa5.
