### ISSUE TITLE
how to get list of leftover args as []string?

### ISSUE THREAD

**Issue by jaybennett89** [alecthomas/kingpin#170]
Hi,

I'm writing a wrapper for a command line tool and I would like to parse out my kingpin args and then pass all remaining args down to the command line tool. How can I do this?

I tried using the Arg().Strings() way, as suggested in the IPs example of the README. However it did not like seeing actual flags:

`error: expected positional arguments <extra-args> but got '--flag-name', try --help`

**Comment by alecthomas** [comment]
To pass args that look like strings you'll need to use `--` to delineate them:

```
mycmd --flag0 --flag1 -- arg0 --arg1
```

**Comment by alecthomas** [comment]
I should clarify that you can actually achieve this with `Application.ParseContext(args)`. This will error, but the returned context has a `HasTrailingArgs()` method, and `Next()` will let you traverse the unparsed arguments, or slice them out with the `.Index`. You'd need to split out the remaining args, then re-parse the flags for kingpin.

**Comment by a-palchikov** [comment]
@alecthomas Do you have a working example of your idea using `HasTrailingArgs` and whatever else APIs you're suggesting?
I have not found a way to slice anything as no `.Index` exists on `ParseContext` and `Application.Parse` seems to be partially implemented with unexported fields in `ParseContext` that makes it impossible to replicate externally with its `ParseContext` API.

**Comment by alecthomas** [comment]
@a-palchikov looks like you're right and that it would need to expose `.args` via a method. If you'd like to send through a PR I will merge it.

**Comment by a-palchikov** [comment]
Sure, let me work something out.
