### ISSUE TITLE
not installed from gopkg.in (

### ISSUE THREAD

**Issue by LuckySB** [alecthomas/kingpin#171]
go get gopkg.in/alecthomas/kingpin.v2
and no more output, wait for 30 min - nothing

ps ax
23708 pts/3    Sl+    0:00 go get gopkg.in/alecthomas/kingpin.v2
23725 pts/3    S+     0:00 git clone https://gopkg.in/alecthomas/kingpin.v2 /root/gocode/src/gopkg.in/alecthomas/kingpin.v2
23726 pts/3    S+     0:00 git-remote-https https://gopkg.in/alecthomas/kingpin.v2 https://gopkg.in/alecthomas/kingpin.v2
23728 pts/3    S+     0:00 git fetch-pack --stateless-rpc --lock-pack --thin --no-progress https://gopkg.in/alecthomas/kingpin.v2  efs/heads/master  efs/heads/v1  efs/h

**Comment by alecthomas** [comment]
There's not much I can do about that...
