### ISSUE TITLE
Option to manually set help wrap width

### ISSUE THREAD

**Issue by saveman71** [alecthomas/kingpin#179]
Hi!

Say I have the following:

```golang
package main

import (
	"gopkg.in/alecthomas/kingpin.v2"
)

var (
	port = kingpin.Flag("port", "Specifies the port number that the server will listen and serve at.").Short('p').Default("8080").Int()
	directory = kingpin.Flag("directory", "Specifies the directory that the server will use to read/write requested files. Default is the current directory when launching the application.").Short('d').Default(".").ExistingDir()
)


func main() {
	kingpin.Parse()
}
```

Which generates the following help message:

```
usage: main [<flags>]

Flags:
      --help         Show context-sensitive help (also try --help-long and --help-man).
  -p, --port=8080    Specifies the port number that the server will listen and serve at.
  -d, --directory=.  Specifies the directory that the server will use to read/write requested files. Default is the current directory when launching the application.
```

How could I break the last argument (-d) before the second sentence, so the output would be:

```
usage: main [<flags>]

Flags:
      --help         Show context-sensitive help (also try --help-long and --help-man).
  -p, --port=8080    Specifies the port number that the server will listen and serve at.
  -d, --directory=.  Specifies the directory that the server will use to read/write requested files.
                     Default is the current directory when launching the application.
```

I tried with a `\n` but it doesn't change anything. I'm new to golang, so I might be missing something obvious, sorry in advance.

**Comment by alecthomas** [comment]
Kingpin automatically wraps to the terminal width. There is currently no support for manually setting a maximum width.

**Comment by saveman71** [comment]
Oh, yes didn't try with a smaller terminal. I was confused by this very long line (which is unusual because habitually help messages are hard-wrapped to 80 characters).

In a way :+1: for the dynamic width, but I feel like a manual way of setting the width would be welcomed too, wrapping to 80 characters helps readability (IMO).

Maybe `\n` could force a line break anyway too.

Feel free to close if this is out of scope.

**Comment by alecthomas** [comment]
I think a manual way of setting the width would be handy.

**Comment by alecthomas** [comment]
This is fixed in v3-unstable. You can override the width (and indentation) with:

```go
kingpin.CommandLine.UsageContext(&kingpin.UsageContext{
  Width: 80,
})
```

**Comment by quite** [comment]
It seems this possibility is gone now?

**Comment by alecthomas** [comment]
This is in the v3 branch
