### ISSUE TITLE
top level Args while using commands

### ISSUE THREAD

**Issue by Ganneff** [alecthomas/kingpin#180]
Hi,

I currently try to reimplement the commandline handling an application
has using go with your kingpin(v2) interface, and ran against a wall.

It might be im too stupid or I may try something non-supported (and am
also entirely new to Go too), but I ran into:

  can't mix top-level Arg()s with Command()

What I try is having an application have a number of commands, with
some arguments to them - but when none of the commands fit, the
argument is stored in a variable.

Say,

tm s la la   - its doing command s with 2 strings as an arg.

tm ms foo    - command ms, one arg

tm bar       - no command, just one arg.

Here, bar can be *ANY* random string, not predictable, but I need to
know it to handle it.

Is it possible?

Thanks!

Joerg

**Comment by alecthomas** [comment]
Unfortunately this is not yet possible, but I agree it would be very handy. It would also be nice to be able to mix args and commands like so:

```
mycli command0 <arg> command1
```

**Comment by Ganneff** [comment]
Now that would be top, yes.

Hrm, not possible means either a huge change in the ui, which is bad, finding another commandline parser that does support it, implementing my own (oh gosh, brrr) or me using something else to learn go. I guess it will be the latter. :)

Do you think it can be possible in v3? Or is this more for a v4 somewhen?

Joerg

**Comment by alecthomas** [comment]
Ideally for v3, definitely.

**Comment by alecthomas** [comment]
This is implemented in the v3-unstable branch (`gopkg.in/alecthomas/kingpin.v3-unstable`).

**Comment by alecthomas** [comment]
And by "this" I mean the ability to do `command0 <arg0> <arg1> command1 <arg2>`. Interspersed arguments *must* be `.Required()` to avoid ambiguity.
