### ISSUE TITLE
kingpin as standalone package

### ISSUE THREAD

**Issue by rbeathar** [alecthomas/kingpin#181]
I like the use of gopkg.in for versioning. However it appears that kingpin has dependencies on the alecthomas/template and alexthomas/units packages.  kingpin should be packaged with the template and units package included in the vendor directory. This change would allow kingpin to be delivered as a standalone package.

**Comment by alecthomas** [comment]
In general I don't think Go packages should vendor dependencies, and that dependencies should be resolved by the final target. What do you mean by "standalone package"?
