### ISSUE TITLE
v2 always interprets "@" in flag

### ISSUE THREAD

**Issue by r0bj** [alecthomas/kingpin#182]
With V2 cannot pass flag with "@" character as a parameter.
Easy example:

```
package main

import (
	"fmt"
	"gopkg.in/alecthomas/kingpin.v2"
)

var (
	test = kingpin.Flag("test", "test").String()
)

func main() {
	kingpin.Parse()

	fmt.Println(*test)
}
```

Execution result:
```
# go run test.go --test '@test1'
test: error: expected argument for flag '--test', try --help
exit status 1
```

Execution result using V1:
```
# go run test.go --test '@test1'
@test1
```

Is there a way of passing "@" char as a parameter in V2?

**Comment by alecthomas** [comment]
Yes, this is a known issue. It will be fixed in v3.

**Comment by alecthomas** [comment]
This is fixed in the v3-unstable branch (`gopkg.in/alecthomas/kingpin.v3-unstable`).
