### ISSUE TITLE
Kingpin get stuck if "@" is found in the command line

### ISSUE THREAD

**Issue by onetwogoo** [alecthomas/kingpin#185]
My code (The official example):
```go
package main

import (
        "fmt"
        "gopkg.in/alecthomas/kingpin.v2"
)

var (
        verbose = kingpin.Flag("verbose", "Verbose mode.").Short('v').Bool()
        name    = kingpin.Arg("name", "Name of user.").Required().String()
)

func main() {
        kingpin.Parse()
        fmt.Printf("%v, %s\n", *verbose, *name)
}
```

My command: `go run test.go @`

What happens? Nothing! The program just get stuck, without any output.

What's expected? The library reports invalid syntax in command line.

**Comment by alecthomas** [comment]
This is a bug that has already been fixed, but I'd forgotten to push to a new release. I've just tagged v2.2.4, so pull down the latest version and try again.

**Comment by falzm** [comment]
Bug is still present in latest version (v2.2.5, tip of branch `master`)...
