### ISSUE TITLE
v2.2.4 creates a breaking API change from v2.2.3 by changing the argument of FlagClause.Short

### ISSUE THREAD

**Issue by siebenmann** [alecthomas/kingpin#186]
In v2.2.3, `FlagClause.Short()` took a `byte` as the argument; as of commit ea545afe29292738d692fa467690a9a34f61deaa, it now takes a `rune`. This breaks upstream code that was using kingpin via gopkg.in/alecthomas/kingpin.v2, such as gopkg.in/hlandau/easyconfig.v1/ (used in github.com/hlandau/acme):

```
gopkg.in/hlandau/easyconfig.v1/adaptflag/adaptflag.go:227:22: cannot use byte(r) (type byte) as type rune in argument to fl.Short
```

This may be working as intended and thus a 'wontfix', but I figured I would mention it since it seems somewhat at odds with having a gopkg.in/alecthomas/kingpin.v2 import path.

**Comment by alecthomas** [comment]
I'm not sure what's going on, but it looks like this has been fixed in [easyconfig](https://github.com/hlandau/easyconfig/blob/v1.0.16/adaptflag/adaptflag.go#L12). Are you sure you're up to date?

**Comment by siebenmann** [comment]
Yes; this was fixed (or changed) in https://github.com/hlandau/easyconfig/commit/fdbf429072426c82ee22a6617d1e1cec36facac8, after I filed my report. I guess this means you might as well close this report, since reverting to the v2.2.3 API would break easyconfig and anyone else who has updated to the new API.

(Godoc.org suggests that there are [a number of potentially affected packages](https://godoc.org/gopkg.in/alecthomas/kingpin.v2?importers), but not all of them may be active or actively used, or use FlagClause.Short.)

**Comment by alecthomas** [comment]
This would only have affected packages that don't use character literals, so the impact is pretty low.
