### ISSUE TITLE
Using kingpin in test files

### ISSUE THREAD

**Issue by gurupras** [alecthomas/kingpin#187]
I've been having trouble using kingpin in test files.

For example:

    package kingpintest

    import (
            "testing"
            "fmt"
            "github.com/alecthomas/kingpin"
    )

    var (
            httpAddr = kingpin.Flag("http-addr", "HTTP address").String()
    )

    func TestDummy(t *testing.T) {
            fmt.Printf("%s\n", *httpAddr)
    }
    func TestMain(m *testing.M) {
            kingpin.Parse()
            os.Exit(m.Run())
    }

The above works if I call `go test`.

However, it fails if I try to add the `--http-addr` flag or any of the `go test` flags with this.
For example: `go test -v --http-addr localhost:1221` will fail with the error message:  
`serialize.test: error: unknown short flag '-t', try --help`

Could you please add this as an example to either the examples folder or to the README?

**Comment by alecthomas** [comment]
I don't think this is possible, as the standard test package uses the standard flags package, and Kingpin is not compatible with it.

**Comment by saidmasoud** [comment]
@alecthomas what would be the correct way to test kingpin-based apps? I am struggling to find an example in the docs. Any help would be appreciated, thanks!

**Comment by alecthomas** [comment]
@saidmasoud have a look at the kingpin tests themselves.

**Comment by Turing-Chu** [comment]
Hi @alecthomas ，I Encountered the same error

when I output log , it said that the error comes from `kingpin.Parse()` function, 
 ```
$ go test 
utils.test: error: unknown short flag '-t', try --help
exit status 1
FAIL    XXXX/utils    0.322s

```
