### ISSUE TITLE
v2 pass a value, starting with `-` as argument for a flag

### ISSUE THREAD

**Issue by breml** [alecthomas/kingpin#188]
Is there a way (with v2) to provide a value, starting with `-` as argument for a flag?
Currently I get the following error: `error: expected argument for flag '--arg', try --help`

Example:

```
package main

import (
	"fmt"

	"github.com/alecthomas/kingpin"
)

var (
	arg = kingpin.Flag("arg", "arg").String()
)

func main() {
	kingpin.Parse()
	fmt.Println("Arg: ", *arg)
}
```

Execution result:

```
$ ./kingpin-test --arg "-n"
kingpin-test: error: expected argument for flag '--arg', try --help
```

Might be related to #182.

**Comment by alecthomas** [comment]
`--arg=-n`

**Comment by breml** [comment]
Thanks, works like a charm.

**Comment by alecthomas** [comment]
Apologies for the terse response, I was on my phone at the time. Glad it works.

**Comment by breml** [comment]
No worries, I got what I needed and this very quickly, so I was glad I could continue with my work.
