### ISSUE TITLE
Negative value for flag 

### ISSUE THREAD

**Issue by cswank** [alecthomas/kingpin#192]
I'm working on a app that needs to be able to handle negative values for a flag.  
With this definition:

`start     = kingpin.Flag("start", "start").Default("0").Float()`

I get:
```
app --start -100
app: error: expected argument for flag '--start', try --help
```

When I try escaping it:
```
app --start "\-100"
plot: error: strconv.ParseFloat: parsing "\\-100": invalid syntax, try --help
```

Is there a way to pass in negative values to a Float() flag?

**Comment by alecthomas** [comment]
--start=-100

**Comment by cswank** [comment]
aha
