### ISSUE TITLE
Expose the string value for flags

### ISSUE THREAD

**Issue by Gouthamve** [alecthomas/kingpin#201]
Hi, I want to iterate through the flags and then get the registered names and values (as `string`). But `f.Value.String()` gives the pointer value and not the `string`.

Ref: https://github.com/prometheus/prometheus/issues/2993
Relevant code for above: https://github.com/prometheus/prometheus/blob/dev-2.0/cmd/prometheus/main.go#L261-L264

Is there an API through which I can get the string?

**Comment by alecthomas** [comment]
Pushed v2.2.5 out, thanks for the report!
