### ISSUE TITLE
Override composite types

### ISSUE THREAD

**Issue by vbauerster** [alecthomas/kingpin#206]
Consider [following](https://play.golang.org/p/q0ybVN152J) snippet:
```go
package main

import (
	"fmt"
	"time"

	"gopkg.in/alecthomas/kingpin.v2"
)

type Config struct {
	String   string
	Duration time.Duration
	Int      int
	Slice    []string
	Map      map[string]string
}

func main() {
	// Assume cfg gets populated elsewhere, for example reading from config file
	cfg := &Config{
		String:   "test",
		Duration: time.Second,
		Int:      1,
		Slice:    []string{"test"},
		Map:      map[string]string{"key": "test"},
	}
	// Now I want to override the cfg, from command line
	// because it is natural for cmd line params to take precedence over config file
	kingpin.Flag("duration", "duration").DurationVar(&cfg.Duration)
	kingpin.Flag("int", "int").IntVar(&cfg.Int)
	kingpin.Flag("string", "string").StringVar(&cfg.String)
	kingpin.Flag("map", "map").StringMapVar(&cfg.Map)
	kingpin.Arg("slice", "slice").StringsVar(&cfg.Slice)
	kingpin.Parse()
	fmt.Printf("cfg = %+v\n", cfg)
}
```
Output:
```
$ go run main.go --string newtest --duration 3s --int 3 --map "test:one" more test
cfg = &{String:newtest Duration:3s Int:3 Slice:[test more test] Map:map[key:test test:one]}
```
I expected that kingping will override composite types like slices and maps, like it is doing with primitive types, but it doesn't. It is very common situation, when config needs to be overridden by cmd line, so it would be nice to override all types, instead of appending.

Expected Output:
```
$ go run main.go --string newtest --duration 3s --int 3 --map "test:one" more test
cfg = &{String:newtest Duration:3s Int:3 Slice:[more test] Map:map[test:one]}
```

**Comment by alecthomas** [comment]
This is intentional, so it won't be changing at this stage, but the idea behind it is that each flag sets a value on the target. So for a map type, this sets a key, for a slice type this appends a value.

Additionally, what would be the behaviour with the following command-line:

```
$ go run main.go --map test:one --map test2:two
```

I think it's more consistent to assume that each flag would set the key to the value, rather than have the first flag reset the map, then subsequent flags set keys.
