### ISSUE TITLE
@<file> should skip empty lines

### ISSUE THREAD

**Issue by cimnine** [alecthomas/kingpin#210]
## Expected Behaviour
When there's an empty line in a `@<file>`, kingpin should skip that line.

## Current Behaviour
Currently it errors: `error: unexpected , try --help`.

## Reasoning
Empty lines are common at the end of files, but might also be useful to group similar flags together, so that they are easily visually distinguishable.

**Comment by mxk1235** [comment]
this change isn't in 2.2.6.

**Comment by mxk1235** [comment]
@alecthomas can this make it into a dot version release, or do i need to fork the repo to get it?

**Comment by alecthomas** [comment]
Fork... or just use master?
