### ISSUE TITLE
Optionally Required flags

### ISSUE THREAD

**Issue by tc-turner** [alecthomas/kingpin#214]
I may be missing it in the docs but is it possible to have a flag be required *only if* another flag was not passed?

For example, I want to support loading a user defined config file OR pass details in on the command line, so if the user passes `--config` they don't need to supply `--host` or other flags.

**Comment by alecthomas** [comment]
For that specific case, you probably want to use the new [Resolver API](https://github.com/alecthomas/kingpin/tree/v3-unstable#configuration-files-and-other-external-sources-of-flagargument-values) in Kingpin V3. Included is a JSON resolver, but you could use any configuration format you prefer.
