### ISSUE TITLE
Support time.Time parsing

### ISSUE THREAD

**Issue by kaoet** [alecthomas/kingpin#220]
I would like to define a flag with [`time.Time`](https://godoc.org/time#Time) as type.

```go
startTime := app.Flag("startTime", "Time to start").Default("2017-01-02 12:34:52").Time("2016-01-02 15:04:05")
```

Where `2016-01-02 15:04:05` is the layout passed to [`time.Parse`](https://godoc.org/time#Parse)

**Comment by alecthomas** [comment]
Fixed in v3-unstable branch.
