### ISSUE TITLE
adjusting the default help behaviour

### ISSUE THREAD

**Issue by tcurdt** [alecthomas/kingpin#221]
## "-h"

The docs state just
```
kingpin.CommandLine.HelpFlag.Short('h')
```
but I am not quite sure what to do with it.
Just calling it does not seem to work.
Would be great to expand the docs on that.

## always use "--help-long"

Is there a way to always print "--help-long" also for "--help"?
I am not a fan of having two separate version for the help.

**Comment by alecthomas** [comment]
> Just calling it does not seem to work.

Calling `.Short('h')` adds `-h` as a short option to the help flag. To clarify, what were you expecting it to do?

> Is there a way to always print "--help-long" also for "--help"?

To change the default help template you should use [UsageTemplate(template)](https://godoc.org/gopkg.in/alecthomas/kingpin.v2#UsageTemplate), passing one of the [predefined templates](https://godoc.org/gopkg.in/alecthomas/kingpin.v2#pkg-variables) (`LongHelpTemplate` in your case).

**Comment by alecthomas** [comment]
Customising help output is described [here](https://github.com/alecthomas/kingpin#custom-help).

**Comment by tcurdt** [comment]
@alecthomas the `.Short('h')` in theory is obvious - but the "help" flag is generated automatically.
The docs just say `kingpin.CommandLine.HelpFlag.Short('h')` and it's not exactly clear how that is meant to be used with e.g.
```
  var (
    app      = kingpin.New("foo", "bad")
    debug    = app.Flag("debug", "bla").Short('d').Bool()
  )
```
Looking at the code it becomes clear that
```
app.HelpFlag.Short('h')
```
does the trick. So it would be great to improve the docs.

Thanks for the help with the template. I didn't realize this is due to switching templates. And indeed `app.UsageTemplate(kingpin.LongHelpTemplate)` does the trick.

The only thing that still does not make much sense is the `(also try --help-long and --help-man)`. Looking at the code I see in `app.go`

```
	a.HelpFlag = a.Flag("help", "Show context-sensitive help (also try --help-long and --help-man).")
	a.HelpFlag.Bool()
	a.Flag("help-long", "Generate long help.").Hidden().PreAction(a.generateLongHelp).Bool()
	a.Flag("help-man", "Generate a man page.").Hidden().PreAction(a.generateManPage).Bool()
```
which is a bit too static for my taste.

I don't want a `Flag("help-long")` at all - and I would love to get the `(also try --help-long and --help-man)` out of the description.

**Comment by alecthomas** [comment]
> I don't want a Flag("help-long") at all - and I would love to get the (also try --help-long and --help-man) out of the description.

This is fixed in [v3-unstable](https://godoc.org/gopkg.in/alecthomas/kingpin.v3-unstable).

**Comment by tcurdt** [comment]
Thanks!
