### ISSUE TITLE
Incorrect handling: when the value of Flag is negative

### ISSUE THREAD

**Issue by liupengs** [alecthomas/kingpin#222]
**Code**
func buildGenParser(genCmd *kingpin.CmdClause) {
       ......
	genCmd.Flag(
		"expires",
		" the expiration time must be equal or greater than -1, in which -1 means never expires.").
		Short('e').IntVar(&expires)
        .....
}

**Command1**
go run app.go gen -e -1

**output1**
error: expected argument for flag '-e'

but when the value of expires is positive number, kingpin  executes properly.

**Comment by alecthomas** [comment]
This is by design.

You need to do `-e-1` (note the lack of space). That is because it's ambiguous whether -1 is a mistaken flag or a parameter.
