### ISSUE TITLE
Allow error introspection?

### ISSUE THREAD

**Issue by carlpett** [alecthomas/kingpin#223]
When having actions tied to commands, it would be useful to be able to distinguish errors in parsing/kingpin errors in general from other errors. That is, given

```go
cmd, err := app.Parse(os.Args[1:])
```

As actions are triggered here, and those errors could be both from bad input and errors in the actions, I would like to differentiate between the cases for error reporting, something like

```go
cmd, err := app.Parse(os.Args[1:])
if err != nil {
	if kingpin.IsParseError(err) { // Or similar
		kingpin.FatalUsage("%v\n", err)
	} else {
		kingpin.Fatalf("%v\n", err)
	}
}
```

This is similar to the `os` package error inspection, an alternative (although given the name, probably less clear to a reader) would to expose the `tError` type so it can be type asserted (as far as I can tell, all errors returned inside kingpin uses this type?)

**Comment by alecthomas** [comment]
For a niche requirement like this I think it would make more sense to do the inverse: wrap action errors in a custom type and have a function for detecting them. You could even use a generic "Action" wrapper function.
