### ISSUE TITLE
v3-unsable env var removing everything before :

### ISSUE THREAD

**Issue by rmb938** [alecthomas/kingpin#227]
I am using v3-unstable with the following flag

```
apiServer := app.CLIApp.Flag("api-server", "API Server [Env: API_SERVER]").Default("http://localhost:8080").Envar("API_SERVER").String()
```

And when I set the environment variable to something like `http://10.0.0.1` the `http:` gets removed. However If I use the flag `--api-server http://10.0.0.1` it works as expected. If I get the environment variable using `os.Getenv("API_SERVER")` it shows the correct string.

Any ideas?

**Comment by rmb938** [comment]
Seem to be something with envarSeparator being used to split the values from a environment variable in buildResolvers

**Comment by rmb938** [comment]
Some more testing.

So since the env var is being split, it only ever uses the last value. so if you set something like `one:two:three` it will only ever return `three`

**Comment by alecthomas** [comment]
Ah. This is intentional for sequences but shouldn't do this for scalar values.

**Comment by alecthomas** [comment]
Sorry that took so long to fix!
