### ISSUE TITLE
How to disable @ / legacy ParseWithFileExpansion?

### ISSUE THREAD

**Issue by sorsasampo** [alecthomas/kingpin#229]
The default with v2 seems to be to handle `@foo` as "read from file foo".

This is somewhat problematic for parsing something like git revisions (`@` is alias for `HEAD`, `@^` for `HEAD^` etc), because you get an error like this:

    error: expected argument for flag '-r', try --help

Is there a way to disable `@` handling either 1) complete or 2) for a flag?

**Comment by alecthomas** [comment]
Unfortunately not. Give v3-unstable a whirl, despite its "unstable" tag it is pretty solid. I have only not released it because some features are not yet complete.
