### ISSUE TITLE
the package level `VersionFlag` and `HelpCommand` is useless

### ISSUE THREAD

**Issue by fate-lovely** [alecthomas/kingpin#231]
the package(v2) inits two variables as follow:

https://github.com/alecthomas/kingpin/blob/947dcec5ba9c011838740e680966fd7087a71d0d/global.go#L8-L17

the `HelpComamnd` and `VersionFlag` are always `nil`.

```go
kingpin.Version("v0.1")
// nil pointer deference
kingping.VersionFlag.Short('v')  
```

**Comment by alecthomas** [comment]
Agreed. These are no longer present in v3-unstable.
