### ISSUE TITLE
Can we make @ expansion optional?

### ISSUE THREAD

**Issue by aboodman** [alecthomas/kingpin#232]
I use kingpin in github.com/attic-labs/noms, and I want to use the '@' char for something else.

**Comment by alecthomas** [comment]
It has already been removed in kingpin.v3-unstable, which is usable now but is lacking some minor features for release as v3.

**Comment by alecthomas** [comment]
Sorry, I should expand a bit further: I can't remove it in v2 as it would be backwards incompatible, unfortunately. But v3 is very closely compatible with v2, and cleans up a lot.

**Comment by aboodman** [comment]
Couldn't you make it optional and default to enabled?

I hacked something up here: https://github.com/attic-labs/kingpin/commit/442efcfac769eef3072317c696afe5861c6f7a15

**Comment by alecthomas** [comment]
Sure, send it through as a PR.
