### ISSUE TITLE
Add support for removing default flags

### ISSUE THREAD

**Issue by noonien** [alecthomas/kingpin#234]
A few flags are [defined by default](https://github.com/alecthomas/kingpin/blob/7e2d1284f714168af95785926b6c7da2aa0abd21/app.go#L62).

I'm trying to use kingpin to parse command lines that are not executed via a terminal, where those commands don't make sense.

A user should be able to opt for those commands not to be added by default.

**Comment by alecthomas** [comment]
The default flags in kijgpin2 can be hidden. Is that sufficient?

Kingpin v3 removed them all except help.

**Comment by alecthomas** [comment]
They are exposed as forth on the application object

**Comment by noonien** [comment]
As far as I can tell, the help flag can be disabled by setting `app.HelpCommand = nil`, even though it's not such a big deal.

My problem is with these flags: help-long, help-man, completion-bash, completion-script-bash, completion-script-zsh

They all force write to stdout, and I can't seem to figure out how to disable them. help-man, and completions are not needed in my case since it's not a CLI app.

**Comment by alecthomas** [comment]
I'm going to close this as it is solved for Kingpin v3.
