### ISSUE TITLE
Same flag for different commands

### ISSUE THREAD

**Issue by Nhoya** [alecthomas/kingpin#236]
Hi, i'm the situation where i'v two commands 

`update` and `delete` and both need the command `url` to be specified, #36 and i was wondering if now there is a more elegant solution since is 3 years old.

Thanks in advance for the help

**Comment by alecthomas** [comment]
With v3-unstable you can use [embedded structs to achieve this](https://github.com/alecthomas/kingpin/blob/v3-unstable/struct_test.go#L78), but no not in general.
