### ISSUE TITLE
Ignoring additional flags

### ISSUE THREAD

**Issue by yosriady** [alecthomas/kingpin#237]
Does the library support ignoring additional flags that are not defined?

Using the simple example:

```
package main

import (
  "fmt"

  "gopkg.in/alecthomas/kingpin.v2"
)

var (
  debug   = kingpin.Flag("debug", "Enable debug mode.").Bool()
  timeout = kingpin.Flag("timeout", "Timeout waiting for ping.").Default("5s").OverrideDefaultFromEnvar("PING_TIMEOUT").Short('t').Duration()
  ip      = kingpin.Arg("ip", "IP address to ping.").Required().IP()
  count   = kingpin.Arg("count", "Number of packets to send").Int()
)

func main() {
  kingpin.Version("0.0.1")
  kingpin.Parse()
  fmt.Printf("Would ping: %s with timeout %s and count %d\n", *ip, *timeout, *count)
}
```

I'd like to be able to ignore additional flags (e.g. --test) which are not defined above instead of returning an `error: unknown short flag`.

**Comment by alecthomas** [comment]
No, that is not possible. You can use `--` to separate parsed arguments from non-parsed, however.

**Comment by themartorana** [comment]
FWIW, this is why we had to choose something else, despite this being a more vibrant solution. The app should be able to ignore unrecognized input, and an option to allow it to do so would be significant - for us anyway.
