### ISSUE TITLE
Support unambiguous arbitrarily ordered flags

### ISSUE THREAD

**Issue by xealot** [alecthomas/kingpin#24]
Is it possible to support flags in any order? For example:

```clitool subcommand arg```

```clitool subcommand --help arg```

```clitool subcommand arg --help```

Reasoning; with complex commands that have many or long arguments it's fairly annoying to have to seek back to before the arguments and add a flag. Especially if that flag is `--help`.

I believe flags can be parsed unambiguously so they could technically be mixed with args, but I know this is probably a complex topic.

**Comment by alecthomas** [comment]
`--help` should currently be special cased to work in most locations, but it's possible there are some cases where it doesn't.

That said, I agree. What I would really like to do is be able to specify any flag for any command/subcommand at any point after the command. That is, if "foo" is a flag for command "foo" (ie. `foo --foo`) then `--foo` can also be specified to any sub-command of foo. eg. `foo bar --foo`. Additionally, `--help` for "bar" should display all ancestor commands and flags.

**Comment by xealot** [comment]
Agree

**Comment by alecthomas** [comment]
I'm not 100% sure this is possible in full.

Imagine this definition:

```go
flag := kingpin.Flag("flag", "").String()
cmd := kingpin.Command("cmd" ,"")
arg := cmd.Arg("arg", "").String()
cmdFlag := cmd.Flag("cmdflag", "").String()
```

Given this command line:

```
cli --flag cmd
```

It's not really possible to determine whether the user meant `cmd` to be an argument to `--flag`, or the command `cmd`.

That said, [this commit](3c91444df6936e75b15dcd6d4af758cc2832618e) in the v2-unstable branch lets you specify flags at *any point after their definition*.

So in the example above one could do:

```
cli cmd --flag=foo --cmdflag=bar
```

I think that is probably sufficient, so I'm going to close this issue. Let me know what you think.

**Comment by xealot** [comment]
While this definition is certainly challenging to program a parser for I don't know if it's ambiguous. If the *Flag* isn't a boolean flag that means it requires an argument so the next token on the stream would be the argument to the flag. This would consume "cmd" in your first example.

If the flag was a boolean it would not consume the next token on the stack and cmd would be interpreted as the subcommand.
