### ISSUE TITLE
Consuming all remaining arguments as a command line entry

### ISSUE THREAD

**Issue by dc0d** [alecthomas/kingpin#240]
The goal is being able to do something like `$ myProgram mySubcmd anotherProgram -f --flag -something someVal`.

How to do that?

I have followed the example and defined:

```go
type slist []string

func (sl *slist) Set(value string) error {
	*sl = append(*sl, value)
	return nil
}

func (sl *slist) String() string {
	return ""
}

func (sl *slist) IsCumulative() bool {
	return true
}
```

And used it. But it is not working, even if every part is put separately inside double quotes like `"ls" "-a"` and it complains about `-a`.

**Comment by alecthomas** [comment]
You shouldn't need a custom type for this, it is natively supported by Kingpin:

```
var someArg = kingpin.Arg("args", "Remaining args.").Strings()
```

And the reason it's complaining about `-a` is because flags can appear in any location, so it is interpreted as a flag that doesn't exist. You need to use `--` to do disable parsing of remaining args:

```
$ app cmd -- ls -a
```
