### ISSUE TITLE
choices

### ISSUE THREAD

**Issue by keith6014** [alecthomas/kingpin#242]
What is the preferred way to implment choices similar to argparse in python (https://docs.python.org/3/library/argparse.html#choices)

**Comment by alecthomas** [comment]
You want [Enum()](https://godoc.org/gopkg.in/alecthomas/kingpin.v2#ArgClause.Enum).

**Comment by keith6014** [comment]
Thanks for the prompt response.

I am doing
```go
app.Flag("color","red,blue").Short('c').Enum("red","blue")
```

Is there a way to auto generate "red blue" when I do --help instead of putting in Flag()?

**Comment by alecthomas** [comment]
Alas, no.

**Comment by keith6014** [comment]
Got it. That would be a nice feature.
