### ISSUE TITLE
differentiate non-value and empty value for optional flags

### ISSUE THREAD

**Issue by mbenabda** [alecthomas/kingpin#244]
Hi there,

i'm using optional string flags for user-defined filters, and in my case, `""` is a valid value of the property to filter on.

sorry if i missed the feature, but is there a way i can know whether a flag has been passed with an empty value or not passed at all ?

thank you

**Comment by alecthomas** [comment]
The only real way to do that is by having a default sentinel value that can never occur (eg. `.Default("\0")`) and checking whether it has been changed.
