### ISSUE TITLE
Allow short help flag on commands

### ISSUE THREAD

**Issue by KevinSnyderCodes** [alecthomas/kingpin#255]
You can set `-h` as a short flag for `--help` on an application using:

```go
kingpin.CommandLine.HelpFlag.Short('h')
```

But I don't see a way to do this for commands. Is this something that can be supported or is there a way to do this that I'm missing?

**Comment by alecthomas** [comment]
I'm not sure what you're asking for. Are you asking if commands can have aliases? If so, yes you can use `.Alias("foo")`.

**Comment by KevinSnyderCodes** [comment]
Basically I'm wondering if there's an easy way to make:

```sh
mycli mycommand -h
```

Do the same thing as:

```sh
mycli mycommand --help
```

From what I can tell you can only set `-h` as a short flag for `--help` on the application, not on specific commands.

**Comment by alecthomas** [comment]
Aaaah. It’s the same flag so it works everywhere.

**Comment by danlamanna** [comment]
Can this be reopened as a feature request? I would also like `foo bar -h` to show the help page for the bar subcommand, while `foo -h` shows the help page for the entire application.
