### ISSUE TITLE
subcommand structure help

### ISSUE THREAD

**Issue by keith6014** [alecthomas/kingpin#256]
So, I have something like this
```go
var (
app=kingpin.New("cmd")

l = app.command("l")
le=l.Arg("e","E")

s = app.command("s")
se=s.Arg("e","E")
seE=s.Arg("n","number").Int()

)
```

My intention is to have something like this
```bash
cmd l production 
cmd s production apple # s is the subcommand, production is an environment, target is apple
cmd s production apple 10 # s is the subcommand, production is an environment, target is apple with 10 objects
```

How can I setup a structure in kinpin for something like that?

**Comment by alecthomas** [comment]
You can't do that unfortunately. Variable arguments can't be interspersed with commands.

If you're feeling adventurous you could try [Kong](https://github.com/alecthomas/kong#branching-positional-arguments), which has a solution for this exact problem, among others.
