### ISSUE TITLE
Improve documentation for Dispatch() and FullCommand()

### ISSUE THREAD

**Issue by fluffysquirrels** [alecthomas/kingpin#27]
I wanted to define my kingpin commands with a pattern where adding a new command only required adding new code (i.e. not modifying an existing switch statement), and also I didn't need to duplicate a string constant for my command name.

I propose additions to the kingpin API to support a similar pattern along the lines of this example:

```go

// my-app.go:
var app kingpin.Application = kingpin.New("my-app", "My app")a

func main() {
	cmd, err := app.Parse(os.Args[1:])
	if err != nil || cmd == "" {
		app.Usage(os.Stderr)
		return
	}
 
	app.RunAction(cmd)
}
```

```go
// my_job.go:
func init() {
	cmd := app.Command("greet", "Greet a user")
	argGreetName := cmd.Arg("greet-name", "Name of user to greet").Required().String()
	cmd.Action(func() {
		fmt.Printf("Hello, %s!", *argGreetName)
	})
}
```

The new kingpin interfaces could be:
```go
// Set the action function for a command
func (*CmdClause) Action(action CommandAction) {}

type CommandAction func(*ActionContext) (interface{}, error)

type ActionContext struct {
	Application *Application
	Command *CmdClause
	// Other stuff here?
}

// Returns whatever values the CommandAction returned.
// cmdName should be a result from Application.Parse()
// Panics if cmdName isn't the name of a registered command, as this is a programmer error.
func (*Application) RunAction(command string) (interface{}, error) {}

// Parses arguments and prints usage on parse error or runs RunAction.
// Other possible names for this function: Run, ParseAndRun, DefaultRun.
func (*Application) ParseAndRunAction(args []string) (interface{}, error) {}
```

Any thoughts?

Happy to write this up as a PR if people like the idea.

**Comment by alecthomas** [comment]
There is already a `.Dispatch()` hook on flags and commands. Is this sufficient?

eg.

```go
cmd := app.Command("greet", "Greet a user").Dispatch(func(*ParseContext) error {
  println("hi")
})
```

Also, you don't need to duplicate string constants. Just use `cmd.FullCommand()` in the case statements.

**Comment by fluffysquirrels** [comment]
Dispatch looks good. On glancing at the code the ParseContext parameter type made me think it was for dispatching parsing, not running the commands themselves. I'd like to add documentation to this.

I'd missed `cmd.FullCommand()`, yes that would help things. I see it's used in README.md but missing in the godoc example. I'd like to update the godoc example as well.

Those two are a big improvement, thanks for pointing them out.

This still doesn't get rid of the switch statement, which I think would be a big improvement. Would you be interested in a PR to add the documentation I mentioned above and dispatch automagically to your commands' Dispatch handlers?

**Comment by alecthomas** [comment]
More documentation is always better!

`Dispatch()` is called after a command is parsed, so you shouldn't need a switch statement AFAICT. Unless I'm missing something?

**Comment by fluffysquirrels** [comment]
I'm so sorry for wasting your time on this. I was scanning the code by using the Github search tool with the keyword `dispatch`, which it turns out only shows a few matches per file. That'll teach me for not using grep! Looking again I can see the unit test to verify `cmd.Dispatch()` is called.

I'll submit a PR to update some of the documentation, which will hopefully make these best practices more discoverable.

**Comment by alecthomas** [comment]
No problem! As you say, documentation is a bit lacking :)
