### ISSUE TITLE
v2 flag do not  get value

### ISSUE THREAD

**Issue by daixiang0** [alecthomas/kingpin#271]
I meet a confused case, the flag with config always empty:
```
var (
	app = kingpin.New("logcli", "A command-line for loki.")

	config = app.Flag("config", "Logcli config.").Default("").String()

	addr, username, password *string
...
)

func main() {
	// get val from config file
	cfg, err := getConfig(*config) <===
```

reproduce with below:
```
$ go get github.com/grafana/loki
$ cd $GOPATH/src/github.com/grafana/loki
$ go build ./cmd/logcli
$ ./logcli --config="xxxx" labels app
```
you can see logcli never read "xxxx" which `--config` specify.

**Comment by alecthomas** [comment]
I'll need a more self-contained example.

**Comment by alecthomas** [comment]
Well, actually I do see the problem. You're using a flag *before* calling `kingpin.Parse()`. That will never work.

**Comment by daixiang0** [comment]
https://github.com/grafana/loki/blob/master/cmd/logcli/main.go
@alecthomas but `addr` also before `Parse`, it can get value.

**Comment by daixiang0** [comment]
whole code: https://github.com/grafana/loki/blob/master/cmd/logcli/main.go
@alecthomas thanks, another question, how can i use config flag to read config file in this case?

**Comment by alecthomas** [comment]
Kingpin supports loading flags from files via `@<file>`.
