### ISSUE TITLE
Arguments from file example ?

### ISSUE THREAD

**Issue by dreampuf** [alecthomas/kingpin#28]
I didn't found about the case. Could somebody bring me one? Thanks

**Comment by alecthomas** [comment]
It's simply @<filename> where there is one argument/flag per line. Perhaps the documentation could use some expansion though.

**Comment by alecthomas** [comment]
And use `kingpin.ParseWithFileExpansion()` instead of `kingpin.Parse()` to expand automatically.

**Comment by dreampuf** [comment]
@alecthomas Thank you. 
```bash
# cat config
127.0.0.1
8084
```

one more question, is that passable to using named arguments ? e.g. 

```bash
$ cat config
host=127.0.0.1
port=8084
```

**Comment by alecthomas** [comment]
If by named arguments you mean flags, then yes:

```
--host=127.0.0.1
--port=8084
```

If you're talking about positional arguments, then no it does not support naming.

**Comment by dreampuf** [comment]
Thank you !

**Comment by swill** [comment]
Even with this, there is no example for how to actually use a config file.  Can someone post a CLI example which uses a config file?

**Comment by alecthomas** [comment]
```
$ cat flags
--some-flag
--some-other-flag=some arg
$ myapp @flags
```

**Comment by swill** [comment]
Thanks @alecthomas.  :)

I tried this in combination with command line entries and I got the following:
```
$ cat flags
--some-flag
--some-other-flag=some arg
$ myapp command --pass="xyz" @flags
```

I got:
```
$ myapp command --pass="xyz" @flags
panic: runtime error: slice bounds out of range
```

If I use the `@flags`, does that mean I can't use the CLI as well?

**Comment by alecthomas** [comment]
This is a known issue (#148). @ support is not great :\

**Comment by swill** [comment]
Ahh.  Ok.  I had not seen that issue.  Thanks.

I am able to get it working now if put all commands and subcommands in the file, but not if I add anything in the command line arguments.
