### ISSUE TITLE
Add a cmd.Stdin("blob", "blob input data for the command").Required().Blob()

### ISSUE THREAD

**Issue by balupton** [alecthomas/kingpin#284]
It would be nice if I could do the following:

``` go
encryptCmd.Stdin("message", "the message to encrypt").Required().String()
decryptCmd.Stdin("blob", "the encrypted message to decrypt").Required().Blob()
```

So that way `--help` can show them, and the stdin reading is handled for me.

**Comment by alecthomas** [comment]
Interesting idea, but I feel like that is somewhat outside the scope of Kingpin.
