### ISSUE TITLE
Does not execute a parent command's action

### ISSUE THREAD

**Issue by balupton** [alecthomas/kingpin#286]
It seems that kingpin only executes actions for leafs, rather than parents.

For instance, with the code from https://github.com/textileio/go-textile/blob/a07d47f5e1e9925069b968c68786a6629ae4fdf6/cmd/main.go#L695-L715 this results in:

```
> textile profile set --name="something"
textile: error: must select a subcommand of 'profile set', try --help
```

I would expect this not to be the case, with both `textile profile set --name="something"` and `textile profile set name "something"` working, as they both have actions defined.

**Comment by alecthomas** [comment]
This won't change for v2, but v3-unstable has [OptionalSubcommands()](https://godoc.org/gopkg.in/alecthomas/kingpin.v3-unstable#CmdClause.OptionalSubcommands).

Subcommands can't be optional, though there can be a default subcommand.
