### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by zwhitchcox** [alecthomas/kingpin#289]
Looking for an alternative to the festering pile of shit that is cobra, but it doesn't seem very active.

**Comment by alecthomas** [comment]
No it is not. The last commit was in July...

Also if you're shopping around try https://github.com/alecthomas/kong

**Comment by alecthomas** [comment]
It's just stable now, so there's not much change going on.

**Comment by zwhitchcox** [comment]
Ok, thanks! Sorry, I guess I was looking at releases
