### ISSUE TITLE
Don't show the subcommands in the help output

### ISSUE THREAD

**Issue by niks3089** [alecthomas/kingpin#295]
I have 10 commands and 20 subcommands under each of them. When the user does <myprogram --help>, he is shown the entire output of around 200 lines. I would like to show him just 10 lines of main commands. He can then do <myprogram command --help> to see the 20 other commands. Is this possible?

**Comment by alecthomas** [comment]
See https://github.com/alecthomas/kingpin#custom-help

There are a couple of default templates, but you can write your own.

**Comment by niks3089** [comment]
Thanks will try it out. Also is there a way to limit the output of help to fit to a screen and allow further scrolling if it exceeds?

**Comment by alecthomas** [comment]
That is beyond the scope of Kingpin in my view.
