### ISSUE TITLE
help don't show all default values

### ISSUE THREAD

**Issue by surajnarwade** [alecthomas/kingpin#296]
### Issue:
I have defined flag as below:

```
cmd.Flag("colors", "colors").Default("black", "gray", "red").StringsVar(&c.colors)
```

### Current State:
When I run help, it shows as below,

```
  --clusters=black... ...  colors
```

### Expected State:

```
  --clusters=black, gray, red  colors
```

**Comment by alecthomas** [comment]
You'll need to use a custom help template for this. See https://github.com/alecthomas/kingpin#custom-help for details.

**Comment by surajnarwade** [comment]
@alecthomas , ideally it should show default values instead of dots
