### ISSUE TITLE
gmake: *** [Makefile.common:193: common-unused] Error 1

### ISSUE THREAD

**Issue by udf2457** [alecthomas/kingpin#298]
As part of compiling  `prometheus/node_exporter` on OpenBSD 6.4 using `go` v1.13 and `gmake` (a.k.a. GNU Make 4.2.1) , you get the folowing error with `kingpin` :

```
gopkg.in/alecthomas/kingpin.v2
gmake: *** [Makefile.common:193: common-unused] Error 1
```

**Comment by alecthomas** [comment]
This is an issue with Prometheus build.
