### ISSUE TITLE
App flags forced back to default by command clause flag parse (v2)

### ISSUE THREAD

**Issue by death** [alecthomas/kingpin#30]
Consider this test case:

```go
package main

import (
	"gopkg.in/alecthomas/kingpin.v2-unstable"
	"fmt"
	"os"
)

var (
	app = kingpin.New("test", "Test case.")
	appflag = app.Flag("appflag", "An app flag.").Default("default").String()

	something = app.Command("something", "Some command.")
)

func main() {
	kingpin.MustParse(app.Parse(os.Args[1:]))

	fmt.Printf("App flag is %s\n", *appflag)
}
```

With v1 it works fine, but with v2-unstable:

```sh
$ go run test.go --appflag 123 something
App flag is default
```

**Comment by alecthomas** [comment]
Interesting, I hadn't thought about this case. I'll have to do a pass over all flags and commands before parsing to set the defaults. This is probably a good idea anyway.

**Comment by alecthomas** [comment]
Actually a similar issue will occur with required flags too. Hmm.

**Comment by alecthomas** [comment]
It's a bit disturbing that this didn't get picked up by the existing tests...wow.

PS. Thanks for trying the unstable branch!

**Comment by death** [comment]
All seems to work now, thanks!
