### ISSUE TITLE
Parse and Execute in separated steps?

### ISSUE THREAD

**Issue by edgard** [alecthomas/kingpin#32]
Is it possible to do something like this?

I'd like to use Dispatch/Action but I would like to initialize some stuff first (config file, checks, etc), before actually dispatching the func.

This way I could parse, get, work with the values of flags, etc, initialize my stuff, and then execute. Currently I can do that with the switch, but it would be much easier to just use dispatch if this was possible.

Or maybe a .Before() and .After() that would be called before/after Dispatch. That would be awesome aswell.

Doable?

**Comment by alecthomas** [comment]
Can you expand on what the use case for this is?

**Comment by edgard** [comment]
One of the most common case for me is loading a config file using a flag: --config=/etc/whatever.json

If I use Dispatch/Action, I have to initialize the config file load from inside each function dispatched.

**Comment by alecthomas** [comment]
Okay. So it seems like you'd be okay with all the values being fully populated before the Dispatch function is called?

If so, that is good news, because that's what will be happening [here](https://github.com/alecthomas/kingpin/blob/v2-unstable/app.go#L269) soon! At the moment value population, dispatch and validation all occur intermingled (as you've found), but this will be split into three distinct passes.

**Comment by edgard** [comment]
Sure! It does help a lot. I would still need to call my own initialization from inside the functions, but at least that makes it possible to do so!

I think this might impact other use cases as both codegangsta's cli and cobra implements something similar:

https://github.com/codegangsta/cli/blob/master/app.go#L35-L40

https://github.com/spf13/cobra/blob/master/cobra.go#L34-L39

https://github.com/spf13/cobra/pull/53

**Comment by alecthomas** [comment]
For your `--config=file` flag, a more idiomatic solution would be to make a [custom parser](https://github.com/alecthomas/kingpin#custom-parsers). Create one that returns your parsed config structure.

**Comment by alecthomas** [comment]
I think what you want to achieve should be possible in [v2-unstable](https://github.com/alecthomas/kingpin/tree/v2-unstable) by using the top-level `Application.Action(f)` callback. This would let you load configuration settings before any other actions are called.

**Comment by edgard** [comment]
Awesome!! Thank you very much! :+1:
