### ISSUE TITLE
Make os.Exit(0) on help optional.

### ISSUE THREAD

**Issue by james-lawrence** [alecthomas/kingpin#33]
Currently the Help command forces an exit of the application. There a way we can override the dispatch behaviour of help so it doesn't exit?

**Comment by alecthomas** [comment]
It happens that I am currently refactoring the help, so I'll bear this ticket in mind while I do so.

**Comment by alecthomas** [comment]
Fixed in v2-unstable (gopkg.in/alecthomas/kingpin.v2-unstable).

**Comment by james-lawrence** [comment]
btw thanks thomas =)
