### ISSUE TITLE
Create a new tag please?

### ISSUE THREAD

**Issue by stapelberg** [alecthomas/kingpin#332]
The latest tag is v2.2.6 from 2017.

I believe for gopkg.in to pick up the contents of the master branch, a new tag needs to be added.

Could you please create a new tag? Thank you.

**Comment by alecthomas** [comment]
Good idea, tagged v2.3.0

**Comment by stapelberg** [comment]
Thanks for adding the tag! Unfortunately, I can’t actually use the new tag:

```
% go mod init use                             
go: creating new go.mod: module use
% go get gopkg.in/alecthomas/kingpin.v2@v2.3.0
go: gopkg.in/alecthomas/kingpin.v2@v2.3.0: invalid version: go.mod has non-....v2 module path "github.com/alecthomas/kingpin" at revision v2.3.0
```

I believe the reason is that your go.mod file does not end in /v2. The go.mod file should start with “module github.com/alecthomas/kingpin/v2”.

Would you like me to send a PR, or do you just want to update the go.mod yourself? 

Thanks
