### ISSUE TITLE
If a flag is not Required(), it does not show up in main command --help output

### ISSUE THREAD

**Issue by wwalker** [alecthomas/kingpin#35]
If a flag is not Required(), it does not show up in main command --help output; it only shows up in the --help for that specific sub-command.  Can this behavior be controlled (I would prefer to have the full flags list in the help at the top level, detail on each flag would still remain in the sub-command specific help)

**Comment by alecthomas** [comment]
What I've determined (from numerous people requesting completely opposed help solutions :)) is that there's no "right" solution for everyone. So for [v2](https://github.com/alecthomas/kingpin/tree/v2-unstable) I am currently working on allowing help to be displayed via `text/template`.

**Comment by alecthomas** [comment]
Okay. If you check out the [v2-model](https://github.com/alecthomas/kingpin/compare/v2-unstable...v2-model) branch I'd be interested in seeing if this is sufficient for your help requirements. You can find the template context [here](https://github.com/alecthomas/kingpin/compare/v2-unstable...v2-model#diff-3472cb4e0a973362a7dbc843481a069eR141).

**Comment by alecthomas** [comment]
No response, assuming everything is 👍
