### ISSUE TITLE
Show help when no parameters specified

### ISSUE THREAD

**Issue by eburnette** [alecthomas/kingpin#37]
Using the chat example, when I just run the "chat" command with no arguments I'd like to get the help output as if I had specified "--help".

**Comment by alecthomas** [comment]
This is the behaviour you will see if you use `kingpin.Flag()`, `kingpin.Arg()`, `kingpin.Command()` and `kingpin.Parse()`. The example creates a custom app via `kingpin.New()` and so hands over complete control to the user.

**Comment by eburnette** [comment]
I like using the non-global functions, so how do I get the same behavior in a custom app?

**Comment by alecthomas** [comment]
`
cmd, err := app.Parse(os.Args[1:])
if err != nil {
  app.UsageErrorf(os.Stderr, "%s", err)
} else if cmd == "" {
  app.UsageErrorf(os.Stderr, "expected command")
}
`

**Comment by alecthomas** [comment]
Thinking about this some more, I agree that this is a bug. The behaviour is inconsistent. I'll fix it soon.
