### ISSUE TITLE
Help command not working in v2-unstable

### ISSUE THREAD

**Issue by eburnette** [alecthomas/kingpin#38]
In the chat example, "chat help" and "chat help post" show help in v1 but do nothing in v2-unstable.

**Comment by alecthomas** [comment]
The "help" subcommand isn't supported in v2, only `--help`. This is mainly because of the ambiguity of "help" as a command and an argument, whereas `--help` always works.

But the output is fairly clear I think...

```
$ go run ./examples/chat2/main.go chat help
main: error: expected command but got chat, try --help
```

**Comment by eburnette** [comment]
I'd still like the help command for my cli. Can you suggest a way to implement it?

**Comment by alecthomas** [comment]
I've added it back as a top-level command. Having it only at the top level removes ambiguity but is still useful.

So you can't do `app command help` but you can do `app help command`.
