### ISSUE TITLE
TestParseExistingFile fails on Windows

### ISSUE THREAD

**Issue by eburnette** [alecthomas/kingpin#42]
--- FAIL: TestParseExistingFile (0.00s)
        Location:       parsers_test.go:57
        Error:          No error is expected but got path '/etc/hosts' does not exist

        Location:       parsers_test.go:58
        Error:          Not equal: "/etc/hosts" (expected)
                                != "" (actual)

**Comment by alecthomas** [comment]
Thank you! I'll fix this soon.
