### ISSUE TITLE
Allow empty placeholder

### ISSUE THREAD

**Issue by eburnette** [alecthomas/kingpin#43]
Using code:

   app.Flag("endpoint", "Server endpoint.").PlaceHolder("").Default("http://www.example.com:8080/v1").URLVar(&c.endpoint)

This still prints the default as the placeholder.

  --endpoint=http://www.example.com:8080/v1
                 Server endpoint.

The effect I'm trying to get is for no placeholder to be printed. Because it's long and ugly I want to hide the value from the user.

**Comment by alecthomas** [comment]
Perhaps use "URL" as the placeholder?

**Comment by alecthomas** [comment]
I'm going to close this, because this is intentional behaviour. A word for the placeholder is the correct usage.

**Comment by eburnette** [comment]
That'll work, thanks.
