### ISSUE TITLE
Print help on STDOUT instead of STDERR

### ISSUE THREAD

**Issue by raphael** [alecthomas/kingpin#44]
It would be nice if it was possible to print the help on STDOUT instead of STDERR so that when the help text gets long there is no need to redirect  before piping to less for example. FWIW standard Linux tools don't seem to print help to STDERR (try `ls --help`, `cp --help`).

**Comment by raphael** [comment]
Err nevermind... just ran across the `Writer()` method of `Application` ;)

**Comment by alecthomas** [comment]
The only problem is that kingpin uses the same writer for errors and usage. So I'd either have to allow both an "error" and a "usage" writer to be specified, or write errors to stdout. The current behaviour is not ideal, but it's simple.

**Comment by raphael** [comment]
Yeah what I end up doing at the moment is  setting the writer to stdout, calling Parse then resetting the writer to stderr before running an actual command which is not great.
