### ISSUE TITLE
Ability to make a subcommand the default if none specified

### ISSUE THREAD

**Issue by orospakr** [alecthomas/kingpin#45]
Right now, if you have a Command added to your kingpin.New() app, and no sub-command is specified at runtime, usage is printed and the program aborts.

My attempt to achieve this with the below failed:

```golang
var (
	appCommand          = kingpin.New("myapp", "Yum yum yum.")
	mySubcommand = appCommand.Command("mysubcommand", "Frob the bars")
)

func main() {
	switch kingpin.MustParse(appCommand.Parse(os.Args[1:])) {
	case mySubcommand():
                log.Print("my subcommand was selected")
	default:
		// default action - alas, usage is printed and we never make it here
                log.Print("my default action")
	}
}
```

**Comment by orospakr** [comment]
I get the impression that https://github.com/alecthomas/kingpin/commit/19fc17384e8418cf98c11bd42a6687325ce830ea may have something to do with this ;)

**Comment by alecthomas** [comment]
That change actually made `app.Parse()` consistent with `kingpin.Parse()`, but yeah, some way of specifying a default command could be useful.

**Comment by kosl90** [comment]
Yeah, that will be really helpful sometimes. But I think customized default action is the realy feature, the default command should be one way to do that.

BTW, nice job @alecthomas , I like this package. I will appreciate it if this feature could be supported soon.

**Comment by montanaflynn** [comment]
+1 

I'm using Kingpin in my [Urban Dictionary CLI](https://github.com/montanaflynn/urbandict) and would like to support getting definitions and synonyms with definition being the default command. 

Here's an example:

```
# Get definitions
urbandict hacker

# Get synonyms
urbandict synonyms hacker

# Get definitions
urbandict define hacker
```

**Comment by johnl** [comment]
I'd like to set a default command per subcommand too:

So running "brightbox servers" is an alias for "brightbox servers list", but you can still run "brightbox servers create" etc.

**Comment by alecthomas** [comment]
I've pushed the branch [default_commands](https://github.com/alecthomas/kingpin/compare/default_commands).

This allows a command like this:

    app command --flag subcommand arg

To be used like this:

    app --flag arg

Via a command-line definition like this:

```go
app := kingpin.New("app", "")
command := app.Command("command", "").Default()
flag := command.Flag("flag", "").Bool()
subcommand := command.Command("subcommand", "").Default()
arg := subcommand.Arg("arg", "").Required().String()
```

If you can give it a whirl and let me know if it works, I'd appreciate it.

**Comment by alecthomas** [comment]
I've tagged this as v2-unstable which you can import as `gopkg.in/alecthomas/kingpin.v2-unstable`

**Comment by johnl** [comment]
ah, whoops, I made the mistake of trying to use the v2-unstable *branch* on github to test this and it broke Fatalf :/

But then I figured out it's on the v2.0.14-unstable tag.

So, this is partly successful - it makes the given subcommand the default, but it breaks the help output (none of the subcommands are listed in the help if I make any one of them a default).

**Comment by alecthomas** [comment]
Sorry, I had deleted the old v2-unstable tag locally but not deleted it on github. Fixed. I'll fix the help up shortly.

**Comment by alecthomas** [comment]
Okay it should be fixed. Let me know either way and I'll push the release.

**Comment by johnl** [comment]
Found the change on v2.1.0-unstable, and the help output works now - thanks very much @alecthomas!

**Comment by alecthomas** [comment]
Pushed 2.1.0 to mainline. Thanks for testing.
