### ISSUE TITLE
--no-interaction flag is not recognized

### ISSUE THREAD

**Issue by fgrosse** [alecthomas/kingpin#54]
I want to have `--no-interaction` flag in my program so I created the following code:

```go
package main

import (
	"fmt"
	"os"

	"gopkg.in/alecthomas/kingpin.v2"
)

var (
	app           = kingpin.New("Test", "")
	foobar        = app.Flag("foo-bar", "A flag containing a minus").Default("false").Bool()
	noInteraction = app.Flag("no-interaction", "Do not ask for any user input").Default("false").Bool()
)

func main() {
	kingpin.MustParse(app.Parse(os.Args[1:]))
	fmt.Printf("Foobar: %+v\n", *foobar)
	fmt.Printf("noInteraction: %+v\n", *noInteraction)
}
```

When I run this with `go run example.go --foo-bar` it works as intendended but when I want to use the `no-interaction`  flag kingpin doesnt recognize the flag even though it is listed in `go run example.go --help`

```
$ go run example.go --help
usage: Test [<flags>]

Flags:
  --help            Show help (also see --help-long and --help-man).
  --foo-bar         A flag containing a minus
  --no-interaction  Do not ask for any user input

exit status 1
$ go run example.go --no-interaction
example: error: unknown long flag '--no-interaction', try --help
exit status 1
```

Am I doing something wrong?

**Comment by alecthomas** [comment]
This is a bug but you should be able to work around it with:


interaction = app.Flag("interaction", "Ask for any user
input").Default("true").Bool()


--no-interaction will still work.

**Comment by alecthomas** [comment]
This is a bug but you should be able to work around it with:

```go
interaction = app.Flag("interaction", "Ask for any user
input").Default("true").Bool()
```
--no-interaction will still work.

**Comment by Lupus** [comment]
:+1: We're also hitting this issue

**Comment by alecthomas** [comment]
Here's the logic I think I'm going to implement:

```go
// Both of these will result in a `--no-interaction` flag being visible.
f := kingpin.Flag("interaction", "").Default("true").Bool()
g := kingpin.Flag("no-interaction", "").Bool()
```

``go
// Both of these will result in an `--interaction` flag being visible.
f := kingpin.Flag("interaction", "").Bool()
g := kingpin.Flag("no-interaction", "").Default("true").Bool()
```

Each flag will have both `--<flag>` and `--no-<flag>`.

**Comment by alecthomas** [comment]
I think this is fixed.
