### ISSUE TITLE
Strings() doesn't work with flags

### ISSUE THREAD

**Issue by andrewhamon** [alecthomas/kingpin#55]
According to https://godoc.org/gopkg.in/alecthomas/kingpin.v2#FlagClause.Strings a flag should allow the type to be a list of strings:

```go
func (p *FlagClause) Strings() (target *[]string)
```
> Strings accumulates string values into a slice.

Using the following code:

```go
package main

import (
	"gopkg.in/alecthomas/kingpin.v2"
	"os"
)

var (
	app         = kingpin.New("my-app", "It does cool things!")
	someStrings = app.Flag("strings", "Give me some strings baby!").Short('s').Strings()
)

func main() {
	kingpin.MustParse(app.Parse(os.Args[1:]))
}
```

And running the test app like so: `./test -s hello world`

I get the following error: `test: error: unexpected world, try --help`

This is the help output:
```
usage: my-app [<flags>]

It does cool things!

Flags:
  --help  Show help (also see --help-long and --help-man).
  -s, --strings=STRINGS
          Give me some strings baby!
```

**Comment by alecthomas** [comment]
You have to repeat the flag: -s hello -s world

**Comment by andrewhamon** [comment]
*facepalm* my bad!

Thanks, and keep up the good work!
