### ISSUE TITLE
--version not working with .Required() fields

### ISSUE THREAD

**Issue by lunemec** [alecthomas/kingpin#56]
When I add .Version to my kingpin parser, when there are other .Required fields, instead of printing version on --version, it wants to have the required fields. They should not be required for --version.

I noticed there is a test in flags_test.go, but its missing one assertion at the end of the function and that should be failing right now.

**Comment by alecthomas** [comment]
I can't replicate this. That test (would) fail, but only because `Terminate()` is a noop.

There's sample code included that is basically what you describe, and it also works:

```
[alec@cavern:~/Projects/kingpin]go run ./examples/ping/main.go --version
0.0.1
```

Please reopen if you can provide sample code that doesn't work as expected.

**Comment by lunemec** [comment]
Hmm, I found that this is not a matter of usage, but rather version. I'm using version from gopkg.in (v2.0.10) and that is not working, my code:

    _src   = kingpin.Arg("src", "Source file/directory to copy.").Required().ExistingFileOrDir()
    kingpin.Version(fmt.Sprintf("ecp (Extended copy) %v\n", Version))
    kingpin.Parse()

**Comment by alecthomas** [comment]
You're one minor release behind (2.0.11 is current stable), and it looks like this issue was fixed in 8e35e3623cc99b579374db465356dba6c06a4e73, which is after 2.0.10.

**Comment by lunemec** [comment]
Oh, yes, godep is just behaving not the way I expected :) Thank you!

**Comment by alecthomas** [comment]
No problem!
