### ISSUE TITLE
Distinguishing between required and optional flags in default usage template

### ISSUE THREAD

**Issue by szank** [alecthomas/kingpin#57]
Hi, 
We have a cli application with many (~35) flags. This amount of flags is unfortunately necessary. 
Using the default help template the usage line doesn't display optional flags. It would be nice to print them in brackets, like in man pages : 
usage : app command --required-flag1 --required-flag-2 ( --optional-flag-1 )

also in the flag section there is no differentiation between  required and optional flags. It would be nice if you could add this. 

Last question : 
Would it be possible to add another template, which would print usage section like this : 
usage : app command --flag-1 \
--flag-2 \
--flag-3 \
--flag-4 \

this would greatly increase readability for applications with many flags ( like ours )

Best regards, 
Maciej

**Comment by szank** [comment]
I can try to work on it myself, as we really need those features, but I don't want to fork the repo (additional maintenance work), and would like to consult the upstream repo owner first.

**Comment by alecthomas** [comment]
> We have a cli application with many (~35) flags. This amount of flags is unfortunately necessary. 
> Using the default help template the usage line doesn't display optional flags. It would be nice to print them in brackets, like in man pages : 
> usage : app command --required-flag1 --required-flag-2 ( --optional-flag-1 )

This was an explicit choice. The usage line is meant as a summary, not an exhaustive listing.

> also in the flag section there is no differentiation between required and optional flags. It would be nice if you could add this.

This is a good idea, I'd welcome this change.

> Would it be possible to add another template, which would print usage section like this : 
> usage : app command --flag-1 \
> --flag-2 \
> --flag-3 \
> --flag-4 \

So it would be just a list of flags, or would it be the extended description as well below it?

**Comment by szank** [comment]
For the third proposal: 
It would be just a list of flags, like now.  I was thinking about a situation, when I give my app to another person, and that person calls 
`myApp --help`
then just copies usage section to a text editor and replaces placeholder values with real values. 
This is just a quality of life improvement, when you have many many flags, and it is ton of typing otherwise. 
With 4-5 lines full of command line parameters, it is easy to get lost and forget to override some values in such use case. 

This is obviously not a concern when you have only a few flags, but this is not the case this time. 

Regards, 
Maciej

**Comment by alecthomas** [comment]
That doesn't seem like a bad idea to me. I would be happy to add an extra template that does this.
