### ISSUE TITLE
Can't figure out how to use EnumVar

### ISSUE THREAD

**Issue by johnl** [alecthomas/kingpin#59]
I'm trying to use EnumVar but can't figure out the interface and can't find an example for it.
```
create := token.Command("create", "create a token").Action(cmd.create)
create.Flag("format", "the output format: text, json or curl").Default("text").EnumVar(&cmd.Format, "text", "json", "curl")
```
I'm a bit of a Go newbie so I assume I'm just missing something, but I think an example in the docs would be useful to others!

**Comment by alecthomas** [comment]
Thanks for the heads up, tagged as v2.0.12.

**Comment by johnl** [comment]
Thanks! Pleased to learn I wasn't being daft!
