### ISSUE TITLE
Support optional Arg

### ISSUE THREAD

**Issue by wwalker** [alecthomas/kingpin#60]
I have a need for an optional argument or two.

This program would behave differently based on whether it has 0, 1, or 2 arguments.  I don't see a way to handle that cleanly in kingpin.  I suspect that is because of the multi-level command support. 

Could we add OptionalArg which cannot be followed by anything else (except another OptionalArg)?

      debug =       kingpin.Flag("debug", "Enable debug mode.").Bool(),
      flagged =     kingpin.Flag("flagged", "Enable flagged mode. (make each key name as to whether it came from vault (v) or consul (c)").Bool(),
      productGroup = kingpin.OptionalArg("product-group", "product group to list.").String(),
      template_file = kingpin.OptionalArg("template-filename", "filename of the template file to verify.").String(),

ehj 
ehj group
ehj group template_file

**Comment by alecthomas** [comment]
Arguments are always optional unless .Required(). The default behavior is exactly as you describe, unless I'm misunderstanding.
