### ISSUE TITLE
Short flags for help and version

### ISSUE THREAD

**Issue by montanaflynn** [alecthomas/kingpin#62]
It would be nice if kingpin supported short flags for the builtin `--help`and `--version` flags. The only reason I see not is it might collide with user added `-h` or `-v` but couldn't we check for those? 

If not automatically having them how can I set them myself?

**Comment by alecthomas** [comment]
Yes, you're correct that it was to avoid conflicting with user-defined flags. I just committed ad6e489 and 53a3ee6 which exposes `kingpin.HelpFlag` and `kingpin.VersionFlag`. You can use these to add short flags.

You can try this by importing `gopkg.in/alecthomas/kingpin.v2-unstable`.
