### ISSUE TITLE
default command with arguments is not we want at the most time

### ISSUE THREAD

**Issue by kosl90** [alecthomas/kingpin#63]
I'm pleasure that default command feature is added, however, it seems a problem here.

~~~golang
package main

import (
	"fmt"
	"gopkg.in/alecthomas/kingpin.v2"
)

func main() {
	modules := kingpin.Command("enable", "").Default().Arg("modules", "").Strings()
	fmt.Println(kingpin.Parse())
	fmt.Println(*modules)
}
~~~
if this file is run like "cmd aaa", the output will be:
~~~
enable
[aaa]
~~~

What I expect is "unknown command", isn't you?

Also see [TestDefaultSubcommandWithArg](https://github.com/alecthomas/kingpin/blob/master/cmd_test.go#L123). This looks nice, but I don't think this is what we want at the most time. This behaviour is confusing. I do not known is there any program works like this either.

**Comment by alecthomas** [comment]
I'm not sure what behavior you're after. If you want an error, don't use .Default().

If you can describe what you *expect* rather than what you *don't expect* it would be helpful.

**Comment by kosl90** [comment]
I mean current behaviour is counter-intuitive. Default command should be used when nothing is not specificed, such as ```cmd``` is executed, default command should be executed, if ```cmd aaa``` is executed, aaa should be parsed as unknown command. 

Because ```cmd [flags] <command> [options] [args]```, the command should be specificed explicitly if you want to use it. The default command is used for convenience and compatiblity at the most time.

**Comment by alecthomas** [comment]
If I understand correctly, the behavior you're after occurs when you Default() a command with no arguments. Only if you Default() a command with arguments will you see what you described in your original comment. So if that is correct, just don't Default() commands with args?

It is difficult for me to understand your description though, so perhaps use code with comments to describe what you think should happen if you Default() commands both with and without args.

**Comment by alecthomas** [comment]
> Default command should be used when nothing is not specificed, such as cmd is executed, default command should be executed

If you default a command with no arguments, that is the behaviour you will get.

> if cmd aaa is executed, aaa should be parsed as unknown command.

If you want an error, don't specify a default command, and don't specify one with arguments.

For example:

```go
enableModules := kingpin.Command("enable", "").Arg("modules", "").Strings()
disableModules := kingpin.Command("disable", "").Arg("modules", "").Strings()
list := kingpin.Command("list", "").Default().Bool()
```

```
$ app enable foo bar
enable: [foo bar]
$ app disable foo bar
disable: [foo bar]
$ app
list: [foo bar waz]
```

The only reason you're seeing the behaviour you're seeing is because you're defaulting a command with an argument.

PS. This feature was motivated by #45.

**Comment by kosl90** [comment]
I see what you want to say, I do not use this package in a right way, the current behaviour is correct.

I know [#45](https://github.com/alecthomas/kingpin/issues/45), I'm one of participants too.

But I don't think current behaviour is user-friendly. It is counter-intuitive.

What I expect:
```go
enableModules := kingpin.Command("enable", "").Default().Arg("modules", "").Strings()
disableModules := kingpin.Command("disable", "").Arg("modules", "").Strings()
list := kingpin.Command("list", "").Bool()
```

```shell
$ app enable foo
enable: [foo]
$ app enable
enable: []
$ app
enable: []
$ app enabel  # typo occurs
unknwon command `enabel`
```

**Comment by alecthomas** [comment]
Removing `.Default()` from that example produces exactly the behaviour you want. Args are only *required* if you use `.Required()`.

Regardless, `.Default()` satisfies all the requirements of #45, which seem quite reasonable and intuitive to me (and them). So it won't be changing now unless some major bug crops up.

If you have a command-line you can't express with Kingpin I'd be happy to figure out if it can be supported, but for now I'm going to close this issue. Feel free to mail me or open a new issue for specific requests.
