### ISSUE TITLE
flag parsing prevents using "-" or @FILE in conventional ways

### ISSUE THREAD

**Issue by insasho** [alecthomas/kingpin#65]
I'm a first-time Kingpin user and I love it so far! 

Unix programs often allow users to specify `-` to read from stdin, or allow values to be read from files using @filename syntax. kingpin returns a parse error when `-` is passed as a positional argument, and doesn't allow a curl-style use of `@-` because the @ anywhere on the command line appears to read command line arguments from a file.

The currently implemented behavior is just different enough from expectations to have caused me grief.

Feature requests:
- Allow flags and positional arguments to receive strings prefixed with @ as arguments, as opposed to loading command line flags. For example, if I'm writing a key-value store, it should allow `./main put key @valuefile.txt` to store the contents of valuefile.txt rather than have its contents treated as a command line.
- Refine parser to not treat a single `-` as the beginning of a command line flag.

Thanks!

**Comment by alecthomas** [comment]
These both seem reasonable to me.

Fixing `@` has been on my radar for a while. I think something like `app.FlagsFile(bool)` could work.

**Comment by alecthomas** [comment]
Closing this. It's not fixed, but I'm moving it over to #90.
