### ISSUE TITLE
feature request: Enum() flag types should show enum options in help

### ISSUE THREAD

**Issue by insasho** [alecthomas/kingpin#66]
The help templates do not include the list of possible values when displaying help for enum flags. 

Example:

```
c.Flag("level", "").Enum("info", "warning", "fatal")
```

Could be rendered with `--help-long` as:

```
--level=LEVEL  (options: info, warning, fatal)
```

**Comment by alecthomas** [comment]
Agreed, that is a good idea.

**Comment by alecthomas** [comment]
This is tracked in #90 as "Configurable help. Some people want enums displayed, default values, envars, etc. Maybe help strings should have their own var expansion."
