### ISSUE TITLE
Arg Strings() attempts to parse

### ISSUE THREAD

**Issue by lusis** [alecthomas/kingpin#67]
My understanding of the following:

```go
jobId = kingpin.Arg("jobid", "").String()
argString = kingpin.Arg("argstring", "").Strings()
```
Would allow you to pass `argString` with strings that look like normal args. Yet I seem to be running into an issue:

```
bin/rundeck-run-job 41972a2d-5929-464e-9ba2-fa30cc3591f8 -aws_secret_key ${AWS_SECRET_ACCESS_KEY} -orgname jv-test-org -aws_access_key ${AWS_ACCESS_KEY_ID} 
rundeck-run-job: error: unknown short flag '-a', try --help
```

The Rundeck API for calling jobs, takes arguments in a format that look like arguments (http://rundeck.org/docs/api/#running-a-job)

Am I mistaken that my above example *SHOULD* work or am I using it wrong?

**Comment by alecthomas** [comment]
No, this should not work (and wouldn't work with any other flag parser either that I'm aware of). This is a common problem though, and Kingpin supports the traditional solution to it: use `--` to tell Kingpin that all subsequent arguments should be passed directly.
