### ISSUE TITLE
Feature Request: PostAction

### ISSUE THREAD

**Issue by rgbkrk** [alecthomas/kingpin#69]
It would be nice to have a `PostAction` so that cleanup that needs to occur can happen. There's not a way to defer it in all contexts but it would fit in well with `PreAction` and `Action`.

**Comment by rgbkrk** [comment]
The common PostAction that I want to do is to tell a `tabwriter` to `Flush()` so that the implementer of commands doesn't have to remember to `Flush` it themselves.

**Comment by rgbkrk** [comment]
I just realized I can do cleanup by setting `Terminate` to my own `func`.

**Comment by alecthomas** [comment]
True, but I agree that a `PostAction` would be nice. I think it would be consistent with the current API.

**Comment by alecthomas** [comment]
I've changed my mind about this, I don't think this will be implemented.

**Comment by rgbkrk** [comment]
All good, I handled this directly and haven't had a chance to look back. Thank you @alecthomas.
