### ISSUE TITLE
Don't always list current environment variable in help output

### ISSUE THREAD

**Issue by rgbkrk** [alecthomas/kingpin#70]
When using `OverrideDefaultFromEnvar`, it sticks the literal value of the current environment variable in the help message. If I'm using an API key for the environment variable, it shows that in my help message. People will inevitably copy and paste this, unintentionally leaking their secret. It would be nice if, when using defaults from env, that `--help` listed the named environment variable instead.

**Comment by alecthomas** [comment]
That's a good point. I see two potential solutions:

1. Display `--flag=${ENVAR-default}` (where "default" is from `.Default()`)
2. Add a `.Secret()` modifier that suppresses value output in help.

I'm not sure which I prefer. The first case diverges from the default Kingpin behaviour of always displaying the default value if available. On the other hand, it does also show the environment variable, which is currently not displayed unless explicitly mentioned in the help.

The second case is more explicit.

Thoughts?

**Comment by rgbkrk** [comment]
Bear in mind that I've only worked with kingpin for a couple days (having come from codegangsta/cli, and preferring kingpin's approach *greatly*). 

I'm assuming (1) is about the Go template that outputs the help while (2) would be a modifier just like other `kingpin.FlagClause`?

The `.Secret()` one makes sense and I don't mind showing the user what their current username or other settings are. That's pretty helpful honestly. I just have to hide the ones I don't want printed.

**Comment by alecthomas** [comment]
FYI, you can currently suppress it explicitly with `.PlaceHolder("SECRET")`, so maybe that's sufficient.

**Comment by rgbkrk** [comment]
Oh hey, that'll work.
