### ISSUE TITLE
Provide bash completion

### ISSUE THREAD

**Issue by rgbkrk** [alecthomas/kingpin#75]
Similar to `--help-man`, create a `--help-bash-completion` flag (that is possibly hidden).

I'm assuming this could come out of e.g. the `CmdGroupModel` of `Application.Model()`. Having not looked at the source and only the API, that was just my best guess.

This will probably be an easier PR for me to start up on than the other issues I've opened. :wink:

**Comment by alecthomas** [comment]
I don't use bash, but this is something I've wanted for a while for zsh. I started, but unfortunately the documentation for zsh completion is lacking.

Definitely would be great to have.

**Comment by rgbkrk** [comment]
Oh! If your `zsh` is recent enough, it *should* come with a function called `bashcompinit` that will create the completer for `zsh`. I've set that in #76.

**Comment by heewa** [comment]
Not sure if I should open a separate issue, but is it correct to have hidden cmds completed? If a cmd is marked as hidden from `--help`, maybe it should also be hidden from tab completion.

**Comment by alecthomas** [comment]
Yes, I would say it should be hidden. Commands, flags too.

**Comment by alecthomas** [comment]
I think this is largely complete, just needs some tweaks and bug fixes. Closing.
