### ISSUE TITLE
Does kingpin support -vvv

### ISSUE THREAD

**Issue by jamlen** [alecthomas/kingpin#80]
I've searched around but can't find if kingpin supports some kind of count flag to support using `-vvv`.

So something like:
```go
verbose := kingpin.Flag("verbose", "Enable verbose logging").Short("v").Counter()
```
would result in
```
verbose -> 3
```

**Comment by alecthomas** [comment]
No, but that is a good idea. You could emulate it with the current version by using `.Action(f).Bool()` and increment an integer inside the Action callback.

**Comment by jamlen** [comment]
OK cool, is there an example in the docs of the Action with callback?

**Comment by alecthomas** [comment]
No, but the godocs are self explanatory.
