### ISSUE TITLE
required flags with default from EnvVars in subcommands don't work

### ISSUE THREAD

**Issue by levinalex** [alecthomas/kingpin#91]
I want to use kingpin in one of my apps that uses subcommands and flags that can be set from environment variables.

This does not work for me as expected. If I have required flags in subcommands I get an error instead:

Example: 

```go
package main

import (
	"fmt"
	"os"

	"gopkg.in/alecthomas/kingpin.v2"
)

var (
	app  = kingpin.New("example", "example demonstrating required flags")
	cmd  = app.Command("command", "a subcommand")
	flag = cmd.Flag("foo", "foo").Envar("FOO").Required().String()
)

func main() {
	kingpin.MustParse(app.Parse(os.Args[1:]))
	fmt.Printf("flag: %#v\n", *flag)
}
```

Running this with a flag works as expected. But I can't set the value from an environment variable:

```bash
% go run main.go command --foo=bar
flag: "bar"
% FOO=bar go run main.go command  
main: error: required flag '--foo' with default value that will never be used, try --help
exit status 1
```

**Comment by alecthomas** [comment]
Huh, interesting. There's even [a test](https://github.com/alecthomas/kingpin/blob/9f1f81712f17990442830b3be73aa30250db5549/flags_test.go#L102) for this case, but it appears to only trigger when on a command. Very weird.

**Comment by levinalex** [comment]
wow, thank you for fixing this so fast. :+1:
