### ISSUE TITLE
Provide a list of environment variables to use as fallback (feature request)

### ISSUE THREAD

**Issue by levinalex** [alecthomas/kingpin#92]
I'd like to be able to define a flag that gets its default value from a list of Environment variables (using the first one that's set)

[codegangsta/cli](https://godoc.org/github.com/codegangsta/cli) uses a comma separated string for this.

Would you be open to a pull request that makes the following work?:

```go
app :=  kingpin.New("app","")
workdir := app.Flag("workdir","").Envar("APP_WORKDIR,TMPDIR").String()
```

(this makes the app use `APP_WORKDIR` when it is set, `TMPDIR` otherwise)

**Comment by alecthomas** [comment]
Seems fairly reasonable, though it might be more obvious to just allow `.Envar()` to be called multiple times.

**Comment by levinalex** [comment]
That could break existing code though. What about `.Envar("FOO", "BAR")`?

**Comment by alecthomas** [comment]
How would it break existing code?

**Comment by levinalex** [comment]
I should have written *change behaviour of* instead of *break*. For example I might construct flags with defaults in a package somewhere and override the defaults in the app. Something like:

```golang
func DefaultFlag(cmd *kingpin.CmdClause, name string) *kingpin.FlagClause {
	f := cmd.Flag(name, "")
	// set some defaults for flag, including:
	f.Envar(strings.ToUpper(name))
	
	return f
}

foo := DefaultFlag(command, "foo").EnvVar("BAR").String()
```

Old behaviour: flag is set from `BAR`, new behaviour: flag is set from `FOO` or `BAR`.

**Comment by alecthomas** [comment]
I'm not super concerned about that particular use case TBH. I'd be very surprised if it were used at all.

That said, I'd be fine with `.Envar("FOO", "BAR")`.

**Comment by alecthomas** [comment]
This meshes quite well with the recent change to Default, which is now `Default(default...string)`

**Comment by h0tbird** [comment]
+1 I would like to use this feature.

**Comment by lpadukana** [comment]
+1 I would love to use this for "Use --region, or Genenv("AWS_REGION"), or Genenv("AWS_DEFAULT_REGION")

**Comment by alecthomas** [comment]
That's a very good example.

**Comment by alecthomas** [comment]
Moved to v3 feature list.
