### ISSUE TITLE
Better documentation around Default

### ISSUE THREAD

**Issue by james-lawrence** [alecthomas/kingpin#98]
I often find myself irritated trying to remember the formats for different types when supplying a default.

example)
```
// doesn't work
app.Arg("myarray", "").Default("1,2,3").StringsVar(&v)
// doesn't work
app.Arg("myarray", "").Default("1 2 3").StringsVar(&v)
// Also doesn't work
app.Arg("myarray","").Default("1").Default("2").StringsVar(&v)
// works, in latest version
app.Arg("myarray", "").Default("1", "2", "3").StringsVar(&v)
```

but in general there seems to be very little documentation around the different types of variables you can have.

**Comment by alecthomas** [comment]
Prior to the latest version there was no way to set defaults for a multi-value type, so the first three have never worked. If you can give an example of where documentation could help or, better yet, send a PR enhancing the documentation, that would be helpful.

**Comment by alecthomas** [comment]
Please reopen if you have some suggestions.
